### ISSUE TITLE
Data set is not able to refresh in Power BI service

### ISSUE THREAD

**Issue by immortal11** [migueesc123/PowerBIRESTAPI#100]
Hi,
I used this custom connector and it is working fine in PBI Desktop. When i hosted the dataset in BI service and tried to refresh it then it is showing an issue . When i tried top manually refresh it it shows -

<img width="446" alt="Custom-Connector Error" src="https://user-images.githubusercontent.com/10623280/152802696-c1709edb-15b2-4f14-8e9f-ed3e0224d9ba.png">

and when i tried for the scheduled refresh it shows-

Unable to determine the data source due to unknown functions. When custom connectors are used, the error can happen if gateway doesn't have the extension enabled. Details: Static analysis failed in gateway. gatewayObjectId:b7fb2dc6-f811-4b4e-81ef-9a0a192cebf5, resultCode:FailedWithUnknownFunctions Query contains unknown function name: PowerBIRESTAPI.Navigation Unknown function name: PowerBIRESTAPI.Navigation is a valid Mashup library function name format. Hence fail the operation. .

Data source for Query1
[Discover Data Sources](https://app.powerbi.com/)

Can anyone please suggest something to get rid of this error. @migueesc123

**Comment by migueesc123** [comment]
Hey! 
This is the official article from Microsoft around setting the refresh on the power bi service:

https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors

For issues related to the data gateway and the overall refresh of a dataset in the power bi service, I'd suggest that you get in touch with the Power BI Support team.

The connector doesn't control how things function behind the scenes at the power bi service level. Only Microsoft handles that component.
