### ISSUE TITLE
Gateway Data Source Users call produces error for AD groups without email address

### ISSUE THREAD

**Issue by lbendlin** [migueesc123/PowerBIRESTAPI#104]
Looks like it is possible to add non-email enabled AD groups as gateway connection users. Currently the code produces an error  

Expression.Error: The field 'emailAddress' of the record wasn't found.
Details:
    datasourceAccessRight=Read
    displayName=[name of group]
    identifier=5a3bd1c4-50e9-xxxx-xxxx-e330f563ed51
    principalType=Group

Note: The "identifier" field is filled, with the email address or group GUID.  Might be advisable to add that field to the output.

**Comment by klinejordan** [comment]
Added some error handling to that query that should fix this, can you confirm? @lbendlin

**Comment by klinejordan** [comment]
#105

**Comment by lbendlin** [comment]
@klinejordan confirmed.

**Comment by klinejordan** [comment]
Yeah, that's because these APIs don't support the new roles. There's some undocumented APIs that do, but I hesitate to use those in these connectors
