### ISSUE TITLE
Datamarts break dataflow related methods

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#106]
Created first datamart today. After doing so the datasets using this wonderful connector are broken with the error 
OLE DB or ODBC error: [Expression.Error] The field 'name' of the record wasn’t found.

Further investigation on the GetData function confirms the error that the Get Dataflows in Group method has incomplete data returned for datamarts.

Response for standard dataflow:
![image](https://user-images.githubusercontent.com/19497071/171294527-b66edd47-e68f-48b9-a624-1c950d355d6e.png)

Response for the new datamart: 
![image](https://user-images.githubusercontent.com/19497071/171294592-92952b45-a2cd-4994-b889-ff99b40f0fbf.png)

name element is missing, hence the error.

Can this be worked around to at least ignore the datamarts for now?  The real issue is with the REST method, but this breaks the usage for now. 

Thanks!

**Comment by klinejordan** [comment]
This should be fixed in #107, can you download a new .mez and confirm? @relax528
