### ISSUE TITLE
Dataflows and Dataflowsources API are broken

### ISSUE THREAD

**Issue by weilinwilliam** [migueesc123/PowerBIRESTAPI#108]
M query:
let
    Source = PowerBIRESTAPI.Navigation(),
    AppWorkspace = Source{[Key="AppWorkspace"]}[Data],
    Dataflows1 = AppWorkspace{[Key="Dataflows"]}[Data]
in
    Dataflows1

Get the error below. Went to https://app.powerbi.com/ and could not find PET Labour Requests Dataflow. It appears that the API attempts to retrieve dataflows that I do not have access to.
Expression.Error: The field 'configuredBy' of the record wasn't found.
Details:
    objectId=63dca4ce-d2ef-427e-84e8-c0c46afff945
    name=PET Labour Requests Dataflow
    description=
    users=[List]

**Comment by klinejordan** [comment]
@weilinwilliam have you downloaded the latest .mez file? This bug was also reported in #106 and we have issued a fix. If you are sure you're using the latest custom connector and still experiencing the issue we can continue to look into it.
