### ISSUE TITLE
Verify Version

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#113]
Is there an easy way to determine the version of the .mez file. I thought I had the latest but do not see the new Apps and Apps Users functions.
I download the current mez file, replaced the copy I had and still do not see these , went back into Power BI Desktop and tried the get data and the functions are not there.

I'm also trying to make sure the correction for the datamarts are included as well.

Any ideas?

Thanks

**Comment by klinejordan** [comment]
I can't reproduce this behavior, I see apps and app users in the PBI service administrator folder

**Comment by klinejordan** [comment]
Not sure if you're still able to reproduce this but closing as I haven't heard back from @relax528
