### ISSUE TITLE
[Question] Refresh dataset from Power BI Service

### ISSUE THREAD

**Issue by albertocaa1317** [migueesc123/PowerBIRESTAPI#119]
Hi team,
sorry for this question, maybe it's very basic.
I created a report using this custom connector and I uploaded to our Power BI Service but I can't refresh the dataset.

"Unable to determine the data source due to unknown functions. When custom connectors are used, the error can happen if gateway doesn't have the extension enabled. Details: Static analysis failed in gateway. gatewayObjectId:0b45a305-0720-4f63-b8d1-07fa4bede3f7, resultCode:FailedWithUnknownFunctions Query contains unknown function name: PowerBIRESTAPI.Navigation Unknown function name: PowerBIRESTAPI.Navigation is a valid Mashup library function name format. Hence fail the operation. .
Data source for Query1
[Discover Data Sources](https://app.powerbi.com/) "

Can't be possible to refresh it or have I to configure something?

**Comment by klinejordan** [comment]
In order to facilitate scheduled refresh in the Power BI service, you need to put this custom connector on a gateway server and enable custom connectors on that gateway cluster. 

Here are instructions: https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors

**Comment by albertocaa1317** [comment]
Hi,
after follow the instructions I can configure the datasource with the gateway:
![image](https://user-images.githubusercontent.com/57954993/176842704-06a7ceec-36b6-4477-b64f-72ab7aefb957.png)

But I have this error:
![image](https://user-images.githubusercontent.com/57954993/176842813-6a169bf8-42d7-499c-964a-e90da015464f.png)

Can you know the reason?

Thanks.
