### ISSUE TITLE
[Question] Refresh dataset from Power BI Service #119

### ISSUE THREAD

**Issue by albertocaa1317** [migueesc123/PowerBIRESTAPI#120]
Following #119 

After to put the custom connector on a gateway I have this error to refresh:
![image](https://user-images.githubusercontent.com/57954993/177122148-a3bb6198-15c1-4f1d-8bbe-bde5a641e5bc.png)

![image](https://user-images.githubusercontent.com/57954993/177122337-386243b0-9bf6-4719-8245-4e22e5d383d7.png)

**Comment by klinejordan** [comment]
I cannot reproduce this error - double check that the account you've used for the custom connector in the gateway has the appropriate permissions.

If that doesn't work, I suggest you contact Microsoft for support with enabling custom connectors in gateways as this is a scenario many people have been able to get working without issue.
