### ISSUE TITLE
powerbi won't show this custom connector

### ISSUE THREAD

**Issue by mangchaaBI** [migueesc123/PowerBIRESTAPI#125]
Hi,

Is there anything else that I need to do for this connector to show up? 

Already added it to my custom connector folders and enabled the security setting to allow any extensions to load

**Comment by klinejordan** [comment]
@mangchaaBI the instructions for getting custom connectors to work in Power BI Desktop are here: https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connector-extensibility#custom-connectors

The most common mistake people make are:
1) not naming the Custom Connector folder EXACTLY [Documents]\Power BI Desktop\Custom Connectors
2) not restarting Power BI Desktop before trying to load the connector

Without any kind of screenshots to demonstrate the steps you've taken so far it is extremely difficult to help you troubleshoot.

**Comment by klinejordan** [comment]
Closing due to lack of response - please comment if you're still unable to get this working
