### ISSUE TITLE
Include Workspace ID with Apps 

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#129]
Is it possible to include Workspace ID when retrieving a list of Apps. The name can change so it's no longer in alignment with the Workspace name.
Thanks

**Comment by klinejordan** [comment]
The Apps As Admin REST APIs don't include Workspace ID, and really Apps are related to Reports, not workspaces. And while I'm sure that the workspace-level APIs return the appId field, I'm not 100% sure if the GetGroupsAsAdmin reports array includes the appId field. I'm on parental leave for a few months, so am not in a position to check. But if the GetGroupsAsAdmin reports array includes appId, it's certainly possible to derive workspace ID from report ID.

**Comment by relax528** [comment]
First of all, congrats! Enjoy the time with your growing family. 
Apps do have to do with reports and dashboards, but they live in a workspace (and someday maybe more than one) and when looking at permissions (currently doing a massive cleanup), workspace users present no differently in AppUsers than someone with permission to the app as an individual, I've been able to backdoor it, just was wondering if there wasn't a more straight forward method. Thanks and enjoy your time off!

**Comment by klinejordan** [comment]
Thanls! An yes, technically apps are related to workspaces but only indirectly, through reports and dashboards in the workspace. In the REST API, the appId foreign key is only present in arrays for dashboards and reports, not workspaces. 

I'll leave this open until I get back but if appId is returned by GetGroupsAsAdmin, it should be an easy fix

**Comment by migueesc123** [comment]
@klinejordan is it part of the GetGroupsAsAdmin?

**Comment by klinejordan** [comment]
It is, the field is called appId and just needs to be added to the record expansion for both dashboards and reports.

**Comment by klinejordan** [comment]
Closed with #146
