### ISSUE TITLE
"Unable to start OAuth login for this data source. PowerBINotAuthorizedException"

### ISSUE THREAD

**Issue by SamRockX** [migueesc123/PowerBIRESTAPI#130]
Hi,

I am one of the Gateway Admins for my company. We have about 800 developers and only recently we introduced your connector to them. Obviously everyone loved it! :)
Thank you for creating it!

We found two issues with the connector.
1. When creating a Gateway connection, and making another developer the owner of the connection, they cannot seem to authenticate with their credentials. We get this error - "Unable to start OAuth login for this data source. PowerBINotAuthorizedException". As a remedy, we have to temporarily make them an Admin to pass the OAuth2 login.

2. Secondly we found that we cannot share Gateway connections among developers (added as Users). Eg: Gateway connection is configured with credentials of user 1 with access to Workspace (X, Y, Z) ... we add another gateway user 2 with Workspace access to  (A, B, Z). Now User 2 can only see common workspaces i.e., "Z".. but not A & B. Is there a way to user credentials of the Dataset  owner to authenticate the current API calls instead of Gateway owner?

**Comment by migueesc123** [comment]
hey!

These two fall outside of the scope of what this repo can handle as bugs / issues / suggestions. The connector is effectively setup following the Power Query SDK. You are welcome to contribute and make changes to the connector, but the issues / opportunities that you've identified are at the Power BI service layer and not the connector layer (which the contributors of this repo could take action on).

My suggestion would be to post these in the official Power BI ideas forum or the Power Query SDK repo:
https://ideas.powerbi.com/ (so you can suggest how the REST API could be enhanced and how authenticated should be handled)
https://github.com/microsoft/vscode-powerquery-sdk (so you can suggest how the SDK should be better integrated at the gateway level)

Hope this helps!
