### ISSUE TITLE
CONNECTION PROBLEMS SINCE 01-08-2022

### ISSUE THREAD

**Issue by evertonthiago** [migueesc123/PowerBIRESTAPI#131]
Since 01-Oct-2022 I am facing some trouble when I try to RUN this connector on POWER BI SERVICE.

While on DESKTOP it runs normally, but when I upload to my PBIX to the service / cloud and try to refresh it (or even define the gateway properties) tt shows me error's like "unable to connect", "gateway unreacheble".

I already tested with multiple power bi accounts, and also 3 different power bi personal gateway installed on different computers, and the error keeps runing when I try to run on POWER BI SERVICE

![image](https://user-images.githubusercontent.com/91399858/182452518-1af373f2-789e-46f0-8e0f-bae5bd03a0f6.png)

![image](https://user-images.githubusercontent.com/91399858/182453299-f96f9ac2-e45f-49cb-929b-c0b1a4c30974.png)

![image](https://user-images.githubusercontent.com/91399858/182453509-97dd2ba3-18f4-4f92-8650-d1122dc22487.png)

![image](https://user-images.githubusercontent.com/91399858/182453619-39ea780c-a465-46c8-8a51-3f5e88c124e7.png)

![image](https://user-images.githubusercontent.com/91399858/182453864-17b60023-7c30-42e6-95a3-e1b7ac2497a5.png)

I also tested the gateway connection with another PBIX file (that not user this connector) and it is running normally.

![image](https://user-images.githubusercontent.com/91399858/182454256-eee06beb-708a-438e-a612-e8b057fef475.png)

![image](https://user-images.githubusercontent.com/91399858/182454359-c57114c7-4821-491d-bf21-11778e2e4325.png)

I saw on microsoft documentation provided / updated on 29-july-2022 (https://docs.microsoft.com/en-us/power-query/handlinggatewaysupport) that custom connector must have a test connection handler to work well.

Is there a connection between this error and this "new" microsoft update?

Is there any way to anyworkaround?

**Comment by migueesc123** [comment]
hey!

I've tested the connector today and can't really repro any errors. If you can provide any repro steps, that would be great.

Based on your error message, it appears to be something related to the LIBERACAO_ACESSOS table and something about what happens in that specific query that is coming into issues. Perhaps it could be issues at the gateway level, so you might need to check the gateway logs to further investigate.
