### ISSUE TITLE
Bug in PowerBIRESTAPI.GroupsDataflowUpstreamDataflows()

### ISSUE THREAD

**Issue by ctorri** [migueesc123/PowerBIRESTAPI#133]
Hello all,

I'm a happy user of your connector.
However, I just discovered that PowerBIRESTAPI.GroupsDataflowUpstreamDataflows() function returns an empty table.
Looking into the code, it seems that line #676  is the culprit:

#"Filtered Rows" = Table.SelectRows(#"Expanded value1", each ([Upstream Dataflow ID] = "67be571c-b750-4585-a40c-13ba8afaa345")),

**Comment by migueesc123** [comment]
Thank you for reporting this!

@klinejordan would you mind checking this when you have a chance?

**Comment by klinejordan** [comment]
Fixed in #134. Thanks!
