### ISSUE TITLE
Automatic refresh error

### ISSUE THREAD

**Issue by acs17** [migueesc123/PowerBIRESTAPI#139]
Hi, 
First of all, thank you for this custom connector. It just saved my live, as I'm not good with powershell, so I couldn't do the report by myself without this help.

I used the custom connector with Power BI Desktop without problems, but when I tried to configure automatically refresh on Power BI Service or just do a manual refresh on Power BI Service, i get the following error:

**The connection string used for the mashup data source is invalid**

I added the custom connector to the desktop custom connectors folder, allowed custom connectors on power bi configuration, added the custom connector to the gateway folder... I don't know if I'm missing something.

Very much appreciate some help,
Aleix

**Comment by migueesc123** [comment]
Hey! 

This goes beyond the support that we provide through this repo. My suggestion would be to get in touch with the Power BI support team so they can help you troubleshoot the situation with the gateway. I'm not really familiar with that error message, so I'm not entirely sure how it could've been introduced.

I can confirm that the connector is working as intended with the October release of the gateway.
