### ISSUE TITLE
Connector not showing in PBI Desktop

### ISSUE THREAD

**Issue by Faazie** [migueesc123/PowerBIRESTAPI#14]
Just need some help! I have followed all the steps but some how Power Bi desktop doesnt show the custom connector. Saved the .mez file in Documents\Power BI Desktop\Custom Connectors, without any luck.

We do use MFA!!

**Comment by migueesc123** [comment]
hey!
My apologies as the documentation that I provided is not up to date. Here's one piece that might help you in regards to "enabling uncertified custom connectors":
https://docs.microsoft.com/en-us/power-bi/desktop-connector-extensibility

**Comment by Faazie** [comment]
Sorry mate! I have tried it already without any luck!
You reckon its due to multi factor authentication(MFA)?

**Comment by migueesc123** [comment]
It shouldn't be due to MFA. If the custom connector isn't showing it's because there is something internally with Power BI Desktop that is not letting it show in the 'Get Data' window. Either be a security reason (as described above) or because there is something going on with the Custom Connector that is simply not working correctly.
Just to confirm, you can not see the Custom Connector in the 'Get Data' window, right?

**Comment by Faazie** [comment]
Yes, from get data window it doesn't show the custom connector!
I have reinstalled Power Bi and currently its seating under C:\Program Files\Microsoft Power BI Desktop and Allow any Data Extension is turned on.
My custom connector folder is seating under C:\Users\USERNAME\Documents\Power BI Desktop\Custom Connectors (I had to create this folder manually)

Note: My On-premises data gateway(Personal Mode) shows the **PowerBIRestAPI** connector under Connectors>Custom data connectors.
From Folder: C:\Users\USERNAME\Documents\Power BI Desktop\Custom Connectors

Thanks for your time.much appreciated.

**Comment by migueesc123** [comment]
I'm baffled by this situation. I'm not sure how I could help. Could you try replicating your situation in a different machine?

**Comment by klinejordan** [comment]
Can you try zipping up the contents in the folder yourself to create the .zip file in the proper directory, then renaming to .mez?

**Comment by migueesc123** [comment]
closing the issue. Can't repro. 
@Faazie  if you can give us a step by step process to repro this, we can look into it further. MFA does not affect anything in the Custom Connector. I use it as well and it works flawlessly.

**Comment by reubster** [comment]
I had this issue myself and resolved it as follows. 

On my machine, the path it was checking was ; 
**%OneDrive%**\Documents\Power BI Desktop\Custom Connectors

**Comment by johnsparkmytech** [comment]
I have this issue currently after newly installing VS 2019 and the PowerQuery SDK add in.  I had to manually create the [Documents]\Power BI Desktop\Custom Connectors folder and when I copied a .mez file into the folder the custom connector is not showing in the list in Power BI Desktop.

I have also tried the above mentioned usage of OneDrive as the folder target with no success.

**Comment by rnevenvf** [comment]
For me the problem also persists: I've added the Custom Connectors folder with the .mez file in the following three places (gateway is configured with the first one), but nothing solved it. 

1. C:\Users\bcv02\Documents\Power BI Desktop\Custom Connectors
2. C:\Users\bcv02\OneDrive - Vattenfall AB\Documents\Power BI Desktop\Custom Connectors
3. C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\Custom Connectors

Gateway (personal mode) is the latest version and seems fine, but in Power BI Desktop the custom connector is NOT shown under 'Get Data'. 

In the Power BI Service the dataset seems to refresh, but at the same time also incidentally gives errors...in Power BI Desktop I get the following error:

"Expression.Error: The import PowerBIRESTAPI.Navigation matches no exports. Did you miss a module reference?"

**Comment by RDavis3000** [comment]
2025 here, same issue
