### ISSUE TITLE
Cant refresh when using Gateway in the service

### ISSUE THREAD

**Issue by mariussveen** [migueesc123/PowerBIRESTAPI#140]
Hi,

First of all, this Custom Connector are AWESOME! Thank you so much for developing it.

When I use the Custom Connector with Power BI Desktop, everything is working as expected. But, when I have uploaded it to my Power BI Premium service, and are going to use our Enterprise Gateway its not working.
We have installed the Custom Connector on the gateway, and are allowing Custom Connector on the settings. I am also able to create the source on the gateway, and when I push the status button I get thats its online.

But when I try to refresh I got this error:

{
   "error":{
      "code":"DM_GWPipeline_Gateway_MashupDataAccessError",
      "pbi.error":{
         "code":"DM_GWPipeline_Gateway_MashupDataAccessError",
         "parameters":{
            
         },
         "details":[
            {
               "code":"DM_ErrorDetailNameCode_UnderlyingErrorCode",
               "detail":{
                  "type":1,
                  "value":"-2147467259"
               }
            },
            {
               "code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage",
               "detail":{
                  "type":1,
                  "value":"Unable to connect to the remote server"
               }
            },
            {
               "code":"DM_ErrorDetailNameCode_UnderlyingHResult",
               "detail":{
                  "type":1,
                  "value":"-2147467259"
               }
            },
            {
               "code":"Microsoft.Data.Mashup.ValueError.Detail",
               "detail":{
                  "type":1,
                  "value":"https://api.powerbi.com/v1.0/myorg/groups"
               }
            },
            {
               "code":"Microsoft.Data.Mashup.ValueError.Reason",
               "detail":{
                  "type":1,
                  "value":"DataSource.Error"
               }
            }
         ],
         "exceptionCulprit":1
      }
   }
}"Table":"Workspaces."

Workspaces is the only table in the model. We have tried to restart Gateway, updated to last version. We have also tried to run the rest api calls through PowerShell and this works fine.

I have tried to install a Personal Gateway on my work computer, and then it works. So I guess there need to be something on the server, but we dont get any error messages in the logs.

Have anyone had the same issue? Please help :)

Br
Marius

**Comment by Vild-Kronhjort** [comment]
Hi Marius. 

I have the same problem. It seems to be periodically. If I change the period that I extract data from I can make it go away. I have not been able to find a solution.

**Comment by mariussveen** [comment]
Hi @Vild-Kronhjort,

I see that you write: " If I change the period that I extract data from I can make it go away. "
I guess this is when you try to extract data from the "Activity Events" API ? Because I get this error on every API calls. The example I have postet on the top here is just a simple Get all Workspaces.

I know there is a limitation on the  "Activity Events". You can only get events from 1 day at the time, and its only stored for the last 30 days.

Br
Marius

**Comment by migueesc123** [comment]
could it be that the authenticated user doesn't have the correct admin rights for some of the endpoints? it's difficult to pinpoint exactly what could be happening and this goes outside of the scope of the issues that we try to tackle in this repo as there could be other variables at play when it comes down to the gateway.

I'd suggest that you reach out to the Power BI Support team for troubleshooting help or to get in touch with a Power BI Custom Connector developer to get more concrete help with your specific tenant and configuration.
