### ISSUE TITLE
Can't connect to Power BI for US Gov endpoints

### ISSUE THREAD

**Issue by npherson** [migueesc123/PowerBIRESTAPI#141]
It looks like it is hard coded to go to Power BI commercial. Can it be updated to include the ability to connect to GCC (or GCC High and DOD eventually)?

https://learn.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#power-bi-urls-for-general-site-usage

**Comment by migueesc123** [comment]
you can check the discussion that transpired around this requirement on #68 

There's a couple of blockers to make that happen:
1. I don't have access to any of these environments to fully validate and test the connector
2. The way that it needs to be implemented to work effectively would break things or would add complexity to the current connector and will no longer be a singleton (a singleton is a connector that doesn't require you to enter any parameters)

There might be other alternatives available, but the easiest approach without introducing any complexity would be to clone the connector and modify it based on the environment that you're trying to connect to.

The best solution that I can give you is to modify the connector to have the urls that will work for your specific environment.

You can read more about the AAD authentication kind implementation from the link below:
https://learn.microsoft.com/en-us/power-query/handlingauthentication#azure-active-directory-authentication

**Comment by jlabjlab** [comment]
@npherson late to the party on this one but I have modified the hard coded points to the different gov versions on my branch here: https://github.com/jlabjlab/PowerBIRESTAPI-GCC-GCCH-DOD
