### ISSUE TITLE
Add support for [GetDashboardSubscriptionsAsAdmin]

### ISSUE THREAD

**Issue by b77uw771b** [migueesc123/PowerBIRESTAPI#153]
[](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/dashboards-get-dashboard-subscriptions-as-admin)

The connector already has the API call for [GetReportSubscriptionsAsAdmin]. Can [GetDashboardSubscriptionsAsAdmin] be added too?

**Comment by klinejordan** [comment]
People still used Dashboards? 😉

It definitely can be added but not sure when the next opportunity for one of the contributors to go about adding it. Feel free to fork the repository and create a PR if you want to add it quicker.
