### ISSUE TITLE
InvalidConnectionCredentials when using on Gateway

### ISSUE THREAD

**Issue by rhalabi** [migueesc123/PowerBIRESTAPI#154]
Hello,  I have copied the .mez flle to our Power BI gateway servers and have setup a gateway connection to use for refreshing a few reports using this custom connector. I don't know why some days it works fine and reports refresh successfully via the gateway and other days it fails with the below error.  I have confirmed the gateway connection credentials are correct/working and the account used is a PBI Service Administrator.  The same datasets will refresh ok some days and not others without making any changes.

![image](https://user-images.githubusercontent.com/53341216/222731198-54deb31b-eb81-47b9-ab33-a675c592aa03.png)

**Comment by klinejordan** [comment]
Sounds like an Azure AD issue. I would suggest opening a ticket with Microsoft or contacting someone who can see sign in logs in Azure AD in your company

**Comment by rhalabi** [comment]
Why and how do you say it's an Azure AD issue? If it was an Azure AD issue why does it work and then not work?  Doesn't make sense.

**Comment by rhalabi** [comment]
> Why and how do you say it's an Azure AD issue? If it was an Azure AD issue why does it work and then not work? Doesn't make sense.

Why and how do you say it's an Azure AD issue? If it was an Azure AD issue why does it work and then not work? Doesn't make sense.

**Comment by klinejordan** [comment]
I'm just trying to give you suggestions here as I can't reproduce this behavior.

**Comment by rhalabi** [comment]
> I'm just trying to give you suggestions here as I can't reproduce this behavior.

Thx this is very strange how inconsistent
