### ISSUE TITLE
Tables return errors when accessed as admin user

### ISSUE THREAD

**Issue by 360d-io-labs** [migueesc123/PowerBIRESTAPI#155]
All tables except the "Power BI Service Administrator" tables report an error when accessed as an admin user but are working ok when accessed as a normal user. 

For instance, when trying to access workspaces table as a PBI admin I get the following error:

```
Expression.Error: The column 'Column1' of the table wasn't found.
Details:
    Column1
```
Is this behavior expected? (Admin can only access admin tables) or is it an issue with what is now returned by the API?

**Comment by klinejordan** [comment]
If the account is only a Tenant Admin and isn't actually a member of any workspaces or an admin of any gateways, it's expected behavior. The non-admin tables only return data for workspaces the calling user is a member of
