### ISSUE TITLE
Gateways API issue

### ISSUE THREAD

**Issue by gino-roy** [migueesc123/PowerBIRESTAPI#157]
I'm getting the same error on the 3 Gateway endpoints "The column 'id' of the table wasn't found."  See attached screenshot

![image](https://user-images.githubusercontent.com/37297811/228583278-cb815c59-0f51-4faa-bfdf-38589514ae9c.png)

**Comment by klinejordan** [comment]
Are you a gateway admin?

**Comment by gino-roy** [comment]
Yes, I'm also a PowerBI Admin.
It was functioning and it stopped about a week ago.
Also when I look at the API documentation there is an ID column so don't understand the error

Gino

From: Jordan ***@***.***>
Sent: Friday, March 31, 2023 11:25 AM
To: migueesc123/PowerBIRESTAPI ***@***.***>
Cc: Roy, Gino ***@***.***>; Author ***@***.***>
Subject: [EXTERNE]Re: [migueesc123/PowerBIRESTAPI] Gateways API issue (Issue #157)




EXTERNAL EMAIL - USE CAUTION

COURRIEL EXTERNE - FAITES PREUVE DE PRUDENCE



Are you a gateway admin?

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmigueesc123%2FPowerBIRESTAPI%2Fissues%2F157%23issuecomment-1492121307&data=05%7C01%7Cgroy%40edc.ca%7C2d0deed5e8ed4d6b1d4908db31fc1267%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158730926830595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fp5fP55kzo7ANLS%2BrwzvnYWVQiyV38uJZM%2BtVwQ7kB4%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI4R5E7OJ4JNDPN3VZO3IYTW63ZLTANCNFSM6AAAAAAWMB4POI&data=05%7C01%7Cgroy%40edc.ca%7C2d0deed5e8ed4d6b1d4908db31fc1267%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158730926830595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1yk4AdyqCGVkt5V0mKLoNEtDxhQcYiuMUtWRcvTnLbw%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

This email, and any attachment, is confidential and may contain privileged information. If you are not an intended recipient, please delete this email and all copies and notify us immediately. Any unauthorized use or disclosure is prohibited.
As well, EDC values your privacy. Please see our Privacy Practice<https://www.edc.ca/en/privacy-policy.html> for information about how we handle your personal information.
Ce message et tout document joint sont confidentiels et peuvent contenir de l'information ne pouvant ?tre divulgu?e. Si vous n'en ?tes pas le destinataire, veuillez supprimer ce message et toute copie de celui-ci et nous avertir imm?diatement. Toute utilisation ou communication non autoris?e est interdite.
De plus, EDC attache une grande importance au respect de votre viepriv?e. Veuillez consulter notre ?nonc? de confidentialit?<https://www.edc.ca/fr/about-us/pages/privacy-policy.aspx> afin de conna?tre nos pratiques en mati?re de protection des renseignement personnels.

**Comment by klinejordan** [comment]
what is the payload you get when you use the try it button here: https://learn.microsoft.com/en-us/rest/api/power-bi/gateways/get-gateways

Do all of the values in the array that gets returned have an "id" field

**Comment by gino-roy** [comment]
Hi,

Yes for the Get Gateways they all have an "id" field. There's only 3 gateways
When I call the Get Datasources passing the gateway id from previous call, they all have an "id" field as well. It get the same error message for this call as well

Gino

From: Jordan ***@***.***>
Sent: Friday, March 31, 2023 1:34 PM
To: migueesc123/PowerBIRESTAPI ***@***.***>
Cc: Roy, Gino ***@***.***>; Author ***@***.***>
Subject: [EXTERNE]Re: [migueesc123/PowerBIRESTAPI] Gateways API issue (Issue #157)




EXTERNAL EMAIL - USE CAUTION

COURRIEL EXTERNE - FAITES PREUVE DE PRUDENCE



what is the payload you get when you use the try it button here: https://learn.microsoft.com/en-us/rest/api/power-bi/gateways/get-gateways<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Frest%2Fapi%2Fpower-bi%2Fgateways%2Fget-gateways&data=05%7C01%7Cgroy%40edc.ca%7C2c56bdb71baa44fb87a708db320e29d2%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158808629927511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CzWLq%2BFn7fTmqRgmawbJgDHT%2B3GZppm9auSXEQuvx7Y%3D&reserved=0>

Do all of the values in the array that gets returned have an "id" field

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmigueesc123%2FPowerBIRESTAPI%2Fissues%2F157%23issuecomment-1492339927&data=05%7C01%7Cgroy%40edc.ca%7C2c56bdb71baa44fb87a708db320e29d2%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158808629927511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R5D5oU0X5cQFFShBVGI0%2BPGAyroMJjeFXe9rL5l843I%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI4R5EYE2XA5JTRPOVSVMWLW64IRHANCNFSM6AAAAAAWMB4POI&data=05%7C01%7Cgroy%40edc.ca%7C2c56bdb71baa44fb87a708db320e29d2%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158808629927511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y2WRsHm2T%2F3ufTZlppaB80A6BJXm6qZfY%2F7jDLodA5Q%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

This email, and any attachment, is confidential and may contain privileged information. If you are not an intended recipient, please delete this email and all copies and notify us immediately. Any unauthorized use or disclosure is prohibited.
As well, EDC values your privacy. Please see our Privacy Practice<https://www.edc.ca/en/privacy-policy.html> for information about how we handle your personal information.
Ce message et tout document joint sont confidentiels et peuvent contenir de l'information ne pouvant ?tre divulgu?e. Si vous n'en ?tes pas le destinataire, veuillez supprimer ce message et toute copie de celui-ci et nous avertir imm?diatement. Toute utilisation ou communication non autoris?e est interdite.
De plus, EDC attache une grande importance au respect de votre viepriv?e. Veuillez consulter notre ?nonc? de confidentialit?<https://www.edc.ca/fr/about-us/pages/privacy-policy.aspx> afin de conna?tre nos pratiques en mati?re de protection des renseignement personnels.

**Comment by gino-roy** [comment]
Another thing to note Get Gateways as Admin work fine. I noticed that you don't rename columns for this call

From: Jordan ***@***.***>
Sent: Friday, March 31, 2023 1:34 PM
To: migueesc123/PowerBIRESTAPI ***@***.***>
Cc: Roy, Gino ***@***.***>; Author ***@***.***>
Subject: [EXTERNE]Re: [migueesc123/PowerBIRESTAPI] Gateways API issue (Issue #157)




EXTERNAL EMAIL - USE CAUTION

COURRIEL EXTERNE - FAITES PREUVE DE PRUDENCE



what is the payload you get when you use the try it button here: https://learn.microsoft.com/en-us/rest/api/power-bi/gateways/get-gateways<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Frest%2Fapi%2Fpower-bi%2Fgateways%2Fget-gateways&data=05%7C01%7Cgroy%40edc.ca%7C2c56bdb71baa44fb87a708db320e29d2%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158808629927511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CzWLq%2BFn7fTmqRgmawbJgDHT%2B3GZppm9auSXEQuvx7Y%3D&reserved=0>

Do all of the values in the array that gets returned have an "id" field

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmigueesc123%2FPowerBIRESTAPI%2Fissues%2F157%23issuecomment-1492339927&data=05%7C01%7Cgroy%40edc.ca%7C2c56bdb71baa44fb87a708db320e29d2%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158808629927511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R5D5oU0X5cQFFShBVGI0%2BPGAyroMJjeFXe9rL5l843I%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI4R5EYE2XA5JTRPOVSVMWLW64IRHANCNFSM6AAAAAAWMB4POI&data=05%7C01%7Cgroy%40edc.ca%7C2c56bdb71baa44fb87a708db320e29d2%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158808629927511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y2WRsHm2T%2F3ufTZlppaB80A6BJXm6qZfY%2F7jDLodA5Q%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

This email, and any attachment, is confidential and may contain privileged information. If you are not an intended recipient, please delete this email and all copies and notify us immediately. Any unauthorized use or disclosure is prohibited.
As well, EDC values your privacy. Please see our Privacy Practice<https://www.edc.ca/en/privacy-policy.html> for information about how we handle your personal information.
Ce message et tout document joint sont confidentiels et peuvent contenir de l'information ne pouvant ?tre divulgu?e. Si vous n'en ?tes pas le destinataire, veuillez supprimer ce message et toute copie de celui-ci et nous avertir imm?diatement. Toute utilisation ou communication non autoris?e est interdite.
De plus, EDC attache une grande importance au respect de votre viepriv?e. Veuillez consulter notre ?nonc? de confidentialit?<https://www.edc.ca/fr/about-us/pages/privacy-policy.aspx> afin de conna?tre nos pratiques en mati?re de protection des renseignement personnels.

**Comment by klinejordan** [comment]
yeah that one got included because it uses some undocumented APIs, honestly not sure what's going on with this one, I cannot reproduce but will look into it when I have time.

**Comment by klinejordan** [comment]
If possible can you send me a copy of the payload you get from the Try It button but with any sensitive values scrubbed out?

**Comment by gino-roy** [comment]
Hi,

I found the issue. It has to do with credentials used.
I had switched the credential to a "service account" which is assigned the PowerBI Administrator role. Not sure why it works for all the other calls but not the gateway ones.
When I switched to my personal AAD account, it worked.

The service account was useful for automating data refreshes since my account does not have permanent assignment of the PowerBI Admin role. It needs to be activated everyday

From: Jordan ***@***.***>
Sent: Friday, March 31, 2023 2:41 PM
To: migueesc123/PowerBIRESTAPI ***@***.***>
Cc: Roy, Gino ***@***.***>; Author ***@***.***>
Subject: [EXTERNE]Re: [migueesc123/PowerBIRESTAPI] Gateways API issue (Issue #157)




EXTERNAL EMAIL - USE CAUTION

COURRIEL EXTERNE - FAITES PREUVE DE PRUDENCE



If possible can you send me a copy of the payload you get from the Try It button but with any sensitive values scrubbed out?

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmigueesc123%2FPowerBIRESTAPI%2Fissues%2F157%23issuecomment-1492432190&data=05%7C01%7Cgroy%40edc.ca%7C819710a6ea8a4cff4e0f08db32176cdd%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158848410818337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QL0EOa98sWYDU1lD5mGWRWijO3RRualvdupj2CyeC88%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI4R5EY6PK22TDMTGM7NCD3W64QJ5ANCNFSM6AAAAAAWMB4POI&data=05%7C01%7Cgroy%40edc.ca%7C819710a6ea8a4cff4e0f08db32176cdd%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158848410818337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YQiBcjuR72xBoRuBuNg%2F1liggkekvwad6ZtjxQq%2B1tk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

This email, and any attachment, is confidential and may contain privileged information. If you are not an intended recipient, please delete this email and all copies and notify us immediately. Any unauthorized use or disclosure is prohibited.
As well, EDC values your privacy. Please see our Privacy Practice<https://www.edc.ca/en/privacy-policy.html> for information about how we handle your personal information.
Ce message et tout document joint sont confidentiels et peuvent contenir de l'information ne pouvant ?tre divulgu?e. Si vous n'en ?tes pas le destinataire, veuillez supprimer ce message et toute copie de celui-ci et nous avertir imm?diatement. Toute utilisation ou communication non autoris?e est interdite.
De plus, EDC attache une grande importance au respect de votre viepriv?e. Veuillez consulter notre ?nonc? de confidentialit?<https://www.edc.ca/fr/about-us/pages/privacy-policy.aspx> afin de conna?tre nos pratiques en mati?re de protection des renseignement personnels.

**Comment by klinejordan** [comment]
Guess I should have asked "_Are the credentials you are using_ a gateway admin" in my first question because that would have solved it. :)

Making the service account a gateway admin would allow you to use the Gateway queries

The undocumented, unsupported APIs for gateways also let tenant admins query them, so that's why you're able to see those but that's not true for the supported APIs. They require the identity of a gateway admin, and even tenant admins can't use them unless they are also gateway admins

**Comment by gino-roy** [comment]
And I thought that PowerBI Service Administrator included Gateway Admin privileges.

From: Jordan ***@***.***>
Sent: Friday, March 31, 2023 3:11 PM
To: migueesc123/PowerBIRESTAPI ***@***.***>
Cc: Roy, Gino ***@***.***>; Author ***@***.***>
Subject: [EXTERNE]Re: [migueesc123/PowerBIRESTAPI] Gateways API issue (Issue #157)




EXTERNAL EMAIL - USE CAUTION

COURRIEL EXTERNE - FAITES PREUVE DE PRUDENCE



Guess I should have asked "Are the credentials you are using a gateway admin" in my first question because that would have solved it. :)

Making the service account a gateway admin would allow you to use the Gateway queries

The undocumented, unsupported APIs for gateways also let tenant admins query them, so that's why you're able to see those but that's not true for the supported APIs. They require the identity of a gateway admin, and even tenant admins can't use them unless they are also gateway admins

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmigueesc123%2FPowerBIRESTAPI%2Fissues%2F157%23issuecomment-1492468011&data=05%7C01%7Cgroy%40edc.ca%7Cdb7f70993b41435a78e708db321ba6b3%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158866554992369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=utomxD0XNwNKszq8JX2G0pbdGjs5J3ggAA6ccJAwKO4%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI4R5EZEY53Y5MDQYDS6XYDW64T3NANCNFSM6AAAAAAWMB4POI&data=05%7C01%7Cgroy%40edc.ca%7Cdb7f70993b41435a78e708db321ba6b3%7Cd4167d58713e4e8f8ba2869b5491fb80%7C0%7C0%7C638158866554992369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vABAJe9%2BxDEiYl6nJbZzpIt83kwRduUnrzPNTPuDP5Q%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

This email, and any attachment, is confidential and may contain privileged information. If you are not an intended recipient, please delete this email and all copies and notify us immediately. Any unauthorized use or disclosure is prohibited.
As well, EDC values your privacy. Please see our Privacy Practice<https://www.edc.ca/en/privacy-policy.html> for information about how we handle your personal information.
Ce message et tout document joint sont confidentiels et peuvent contenir de l'information ne pouvant ?tre divulgu?e. Si vous n'en ?tes pas le destinataire, veuillez supprimer ce message et toute copie de celui-ci et nous avertir imm?diatement. Toute utilisation ou communication non autoris?e est interdite.
De plus, EDC attache une grande importance au respect de votre viepriv?e. Veuillez consulter notre ?nonc? de confidentialit?<https://www.edc.ca/fr/about-us/pages/privacy-policy.aspx> afin de conna?tre nos pratiques en mati?re de protection des renseignement personnels.
