### ISSUE TITLE
Unable to signin 

### ISSUE THREAD

**Issue by kishorekumar737** [migueesc123/PowerBIRESTAPI#166]
hi, Can anyone help with below issue? I am using Odata feed option in PowerBI . I am able to run the Odata url (sap) from browser however when i run it from PowerBI using Basic Authentication method. it throws me error , unable to authenticate the credentials provided. i turned ON  the trace at PowerBI side . the trace captures below error
I donot find any issue when i run the query directly in sap system or from browser or gateway client . the issue occurs only when i run the odata feed url from PowerBI
Thanks in advance!

![image](https://github.com/migueesc123/PowerBIRESTAPI/assets/133907370/ab72e086-6883-410a-911d-3819eb522d5f)
The remote server returned an error: (401) Unauthorized.\r\nStackTrace:\n   at Microsoft.Mashup.Engine1.Library.Http.WrappingHttpWebRequest.WrapExceptionResponse[T](Func`1 getValue)\r\n   at Microsoft.Mashup.Engine1.Library.OData.ODataRequest.GetResponse(WebRequest webRequest)\r\n   at Microsoft.Mashup.Engine1.Library.Http.Request.ManualRedirect(IEngineHost host, String resourceKind, Uri uri, CreateWebRequestDelegate createRequest, Func`2 createResponse, WebRequest& webRequest, Int32[] nonErrors)\r\n   at Microsoft.Mashup.Engine1.Library.OData.ODataRequest.<>c__DisplayClass23_0.<GetResponseStream>b__0()\r\n   at Microsoft.Mashup.Engine1.Library.Http.RetryPolicy.Execute[TResult](IEngineHost host, Func`1 func)\r\n   at Microsoft.Mashup.Engine1.Library.OData.ODataRequest.GetResponseStream(IHostTrace trace, String key, Boolean tokenRefreshed)\r\n\r\n\r\n","Exception":"Exception:\r\nExceptionType: Microsoft.Mashup.Engine.Interface.ResourceAccessAuthorizationException, Microsoft.MashupEngine, Version=1.0.0.0

**Comment by migueesc123** [comment]
Hey, this question falls out of the scope of what this repo encompasses. Please use the [Power BI community forum](https://community.powerbi.com/t5/Power-Query/bd-p/power-bi-services) to post this question.

**Comment by kishorekumar737** [comment]
thanks for your response. will post it Powerbi community
