### ISSUE TITLE
Dataset Datasources refresh not working

### ISSUE THREAD

**Issue by mayurvgajera2023** [migueesc123/PowerBIRESTAPI#182]
It loads preview data but when refreshing the data, all the other tables refresh ok but dataset datasources is not refreshing. It keeps waiting for PowerBIRestAPI

**Comment by mayurvgajera2023** [comment]
I think Microsoft has updated the mechanism to pull this data and someone needs to update the code.

**Comment by migueesc123** [comment]
> I think Microsoft has updated the mechanism to pull this data and someone needs to update the code.

This doesn't appear to be the case. You can check their documentation:
https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-datasources

and then the lines of code at the connector level that do the calls:
https://github.com/migueesc123/PowerBIRESTAPI/blob/9d6ca60efa296e1efbdb861b7585c0fb169a4cb3/Power%20BI%20API/PowerBIRESTAPI/PBIAPI.pq#L1048-L1080

I'd recommend checking what response you're getting from the REST API by using something like Fiddler to see the calls and responses at your network level, then seeing if perhaps there's an issue in terms of permissions to that endpoint.

If there isn't, and you're still seeing issues with that particular node - object, then please share the error message that you're getting when you try to run this table in Power BI Desktop and what query you're trying to evaluate.
