### ISSUE TITLE
Adding "workspaceId" to Admin - Apps GetAppsAsAdmin

### ISSUE THREAD

**Issue by gielk** [migueesc123/PowerBIRESTAPI#183]
workspaceId is availible in de API call but is not showing in the results. 

https://learn.microsoft.com/en-us/rest/api/power-bi/admin/apps-get-apps-as-admin

I would like to add this but I don't know how to dot this.

**Comment by klinejordan** [comment]
The ID returned by that API is the App ID, not the workspace ID. Technically, Reports and Dashboards are related to Apps, not workspaces.
