### ISSUE TITLE
Reports 

### ISSUE THREAD

**Issue by bsaragadam** [migueesc123/PowerBIRESTAPI#19]
Underlying error code: | -2147467259 Table: Reports.
-- | --
Underlying error message: | The field 'datasetId' of the record wasn't found.
DM_ErrorDetailNameCode_UnderlyingHResult: | -2147467259
Microsoft.Data.Mashup.ValueError.Reason: | Expression.Error
Microsoft.Data.Mashup.ValueError.embedUrl: | https://app.powerbi.com/rdlEmbed?reportId=######################config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVdFU1QtVVMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQifQ%3d%3d
Microsoft.Data.Mashup.ValueError.id: | 036a5849-16f8-4e9f-805d-298100e6e079
Microsoft.Data.Mashup.ValueError.isFromPbix: | False
Microsoft.Data.Mashup.ValueError.isOwnedByMe: | True
Microsoft.Data.Mashup.ValueError.name: | Mandatory Time Off Self Report
Microsoft.Data.Mashup.ValueError.reportType: | PaginatedReport
Microsoft.Data.Mashup.ValueError.webUrl: | https://app.powerbi.com/groups/50188c72-1ea3-4707-9061-fdeabc8ff73d/rdlreports/####################

Cluster URI: | WABI-WEST-US-redirect.analysis.windows.net
Activity ID: | cea4ab66-a46b-4faf-a9ff-c828328a8165
Request ID: | 3be3315d-064b-c68a-8e61-00ea3d675373
Time: | 2019-11-22 14:45:20Z

Report Refreshing is failing in both desktop and service for paginated reports publishing in the work space as they didnt have the dataset id with the error message. 

Is there any other work around to fix the issue

**Comment by migueesc123** [comment]
Could you please share with us more info about what function from the connector was used to trigger this error?
The field **datasetId** is being referenced in multiple parts of the Custom Connector, we don't really know which of the functions that references the **datasetId** is having the issue for your environment.

**Comment by bsaragadam** [comment]
Hi Miguel, 
Its blocking failing in Reports table in the custom connector

**Comment by migueesc123** [comment]
@klinejordan would you mind taking a look ? Can’t repro

**Comment by klinejordan** [comment]
Fixed - MSFT changed the behavior for Paginated Reports (now showing with a different report type and NULL dataset ID). @bsaragadam Can you validate?

**Comment by bsaragadam** [comment]
yes, its working now 
thank you

**Comment by bsaragadam** [comment]
@migueesc123 / @klinejordan  
Again failing with the same error for the paginated reports 
Is there any change again from MSFT ??

**Comment by klinejordan** [comment]
I am not seeing any failures for paginated reports so I can't reproduce, can you post the error message you're getting?

**Comment by bsaragadam** [comment]
Underlying error code: | -2147467259 Table: Reports.
-- | --
Underlying error message: | The field 'datasetId' of the record wasn't found.
DM_ErrorDetailNameCode_UnderlyingHResult: | -2147467259
Microsoft.Data.Mashup.ValueError.Reason: | Expression.Error
Microsoft.Data.Mashup.ValueError.embedUrl: | https://app.powerbi.com/rdlEmbed?reportId=XXXXXXXXXXXXXXXXXXXXX
&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVdFU1QtVVMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQifQ%3d%3d
Microsoft.Data.Mashup.ValueError.id: | 036a5849-16f8-4e9f-805d-298100e6e079
Microsoft.Data.Mashup.ValueError.isFromPbix: | False
Microsoft.Data.Mashup.ValueError.isOwnedByMe: | True
Microsoft.Data.Mashup.ValueError.name: | Mandatory Time Off Self Report
Microsoft.Data.Mashup.ValueError.reportType: | PaginatedReport
Microsoft.Data.Mashup.ValueError.webUrl: | https://app.powerbi.com/groups/50188c72-1ea3-4707-9061-fdeabc8ff73d/rdlreports/XXXXXXXXXXXXXXXXX
Cluster URI: | WABI-WEST-US-redirect.analysis.windows.net
Activity ID: | 1fd650b0-7582-4ccb-b906-756823ef36cb
Request ID: | a0501f88-2da9-3de4-b09f-0ab90c3f3d2b
Time: | 2019-11-27 16:23:38Z

**Comment by klinejordan** [comment]
Okay, are you sure you're still using the latest version of the connector? I can't reproduce that error, all my paginated reports return a NULL dataset ID as they don't have datasets (that's intended behavior)

**Comment by bsaragadam** [comment]
@klinejordan  Yes its working fine with the latest App and I have the other question to pull the data from Power BI Service Admin table do we need the both TenantRead.All/TenatRead.Write.All permission ??

I have tried with TenantRead.All permission and failing with the error message with 401 unauthorized. 

could you provide the  required permissions for the tenant level to extract the data

**Comment by klinejordan** [comment]
Per https://docs.microsoft.com/en-us/power-bi/developer/power-bi-permissions, you need to grant all permissions, not just read. We don't control what permissions are used and why, we're just following the documentation provided by MSFT.

**Comment by bsaragadam** [comment]
Yes @klinejordan  I have all the above permissions but its failed with Authentication while connecting to the Power BI Service admin table

![image](https://user-images.githubusercontent.com/56641802/69976733-7bb0b780-154f-11ea-844b-a14f648ae429.png)

**Comment by klinejordan** [comment]
For that section you need to be a Power BI service admin role. Are you able to get that role or elevate your privs?

**Comment by bsaragadam** [comment]
@klinejordan  Yes, I have the Power BI Service admin role but getting the above error.

**Comment by bsaragadam** [comment]
![image](https://user-images.githubusercontent.com/56641802/70044339-2eccef80-15e8-11ea-92f1-0a65635b1cbd.png)


Just added the fiddler error message from the fiddler while trying to load the Power BI Service Admin table from the connector

**Comment by bsaragadam** [comment]
@klinejordan I'm having the Power BI Server Admin Role and Tenant.Read.All and Tenant.Write.ReadAll Role Permission role.. do we need any other permissions required.

**Comment by klinejordan** [comment]
The permissions your app registration needs is all documented here: https://docs.microsoft.com/en-us/power-bi/developer/register-app

But here's a screenshot of my app registration so you can try to match. 
![image](https://user-images.githubusercontent.com/48561922/70090049-3b444e80-15ce-11ea-874b-0dc16e333ad1.png)

Also if you're Power BI Service Admin role is a Just In Time privilege (meaning you have to elevate each time you use it - some tenants are configured like this including mine) make sure you've elevated it, not just eligible:
![image](https://user-images.githubusercontent.com/48561922/70090139-6c248380-15ce-11ea-9109-809a0dacfb5c.png)

**Comment by bsaragadam** [comment]
@klinejordan  
I have verified the above permissions and we have all the required permission but We don't have Privileged Identity Management License to our tenant Is there any other way we can elevate the permission or do we need compulsory PIM for Power BI  service admin  to get this custom connector to work ??

**Comment by bsaragadam** [comment]
@klinejordan  do you have any update ?? If we dont have the PIM License and we cannot fetch the data for Power BI service admin table ?? We are the Power BI Service Administrator role but not using the PIM ..

**Comment by klinejordan** [comment]
You don't need PIM to get this to work - i mentioned it because some tenants have it and some don't, and some people forget that they need to activate it, not just be eligible for the role.

I'm not sure I can fix your issue at this point - you may have other networking or authentication or trust settings I'm not aware of, but supporting this connector isn't my full time job.

**Comment by migueesc123** [comment]
hey @bsaragadam !

This repo is mainly taking bugs related to the custom connector itself. To be more specifically, anything that is not working as intended because of something that is just awfully written in our code (usually my fault).

The custom connector was created as a community effort and is provided as is with no warranty under the MIT license, which means that you can also fork it and customize to your needs in the event that you see anything that is missing.

As @klinejordan has said, this appears to be an issue related to permissions on your tenant and not something related to our Custom Connector. I'd highly recommend that you get in touch with your Power BI Admin and provide the pictures that you've seen before in this thread as an example in terms of permissions that should be available in your app for this to work. 

We are not the owners of the data source, so we are unable to provide any diagnostics or further help as to what's happening with your specific case. Ultimately if your Power BI Admin needs further help, I'd recommend that he / she gets in touch with Microsoft to look further into it.

We thank you for reporting the original bug and if you find any other bug or errors in the dataset, please let us know.

**Comment by bsaragadam** [comment]
@migueesc123 @klinejordan  Thanks for the prompt response.. @klinejordan  do you use the MFA for your tenant ?? I'm thinking its blocking for me due to MFA..

**Comment by Oddjobe** [comment]
Hi!
The missing piece in my case was "Grant Admin Consent"
![image](https://user-images.githubusercontent.com/15087494/76245462-3847a280-623c-11ea-8dfe-2addd3e7d142.png)

Thanks for all the awesome work with this connector
