### ISSUE TITLE
Works on Desktop but not in Service

### ISSUE THREAD

**Issue by hideakisuzuki007** [migueesc123/PowerBIRESTAPI#2]
Hi Miguel
I have downloaded and tried your method and it works great on Power BI Desktop, thanks!.
But when I publish it to Power BI Service, then I cannot seem to refresh dataset ( or data source).
I get an error "One or more data source is not supported so cannot schedule to update the dataset"
(The error is in Japanese so this is a rough translation by me)
and "Query contains unknown function name : Power BIRESTAPI.Navigation"

What am I missing or do I need to do something else to use this in Power BI Service ?

<img width="244" alt="20180515_1" src="https://user-images.githubusercontent.com/39077370/40029854-595c19dc-57d6-11e8-934c-ecfcaafce54a.PNG">

**Comment by migueesc123** [comment]
Hey!

Thanks for the kind words! Right now you'll need to set up a Gateway in order to refresh your dataset on the Power BI Service.

[Here's a blog post ](https://www.poweredsolutions.co/2018/04/23/refreshing-a-power-bi-custom-connector-in-the-cloud/)explaining how to make that happen. I can confirm that the Custom Connector is refresh-able this way.

**Comment by hideakisuzuki007** [comment]
Hi Miguel
I have another question, is it possible to refresh data directly from the data source to Power BI Service ? Your suggested method above works but the machine has to be on when data gets refreshed so I am wondering if there is a way to refresh data without using a Gateway.

Thanks !
Hideaki

**Comment by culpgrant** [comment]
Something that works for me is in the PBI file change the privacy level for Python to "Private" and republish.

**Comment by tankepaus** [comment]
Can confirm this is an issue in the Power BI service.
"Unable to refresh the model (id=4862983) because it references an unsupported data source."
Using the on-prem non-personal gateway and have Premium in the service.
