### ISSUE TITLE
Issue with Secret.txt

### ISSUE THREAD

**Issue by migueesc123** [migueesc123/PowerBIRESTAPI#21]
Hey @ImkeF @klinejordan !
Would you guys mind trying out the new version of the connector, but re-enabling the client_secret for the OAuth token?

Every time that I tried with it, it just gave me an error that it couldn't load the ClientSecret.txt file for some odd reason.

My app works totally fine without the need for the client secret, but I just want to make sure that it'll work for you guys as well.

**Comment by stjeloma** [comment]
For me, not working without client_secret.

**Comment by ImkeF** [comment]
Hi @migueesc123 ,
I've added the secret to the StartLogin (new line of code!) and it worked like a charm for me:
![image](https://user-images.githubusercontent.com/18321412/71887707-f10b3b80-313e-11ea-9ea0-db6e57528d31.png)

/Imke

**Comment by stjeloma** [comment]
Thanks @ImkeF for me, only working with "client_secret".

**Comment by ImkeF** [comment]
You're welcome @stjeloma  and thanks for testing. 
Just to be clear: With that adjustment, it works for you?

**Comment by stjeloma** [comment]
Yes, only include your line number 730 in PBIAPI.pq for client_secret!!!

**Comment by ImkeF** [comment]
Great! Thanks for confirmation!

**Comment by migueesc123** [comment]
Pretty weird how it doesn’t work for me.
@klinejordan when you get a chance, could you please test the new code ?

**Comment by klinejordan** [comment]
Not working for me either way. It's only ever worked for me with the client_secret=client_secret in line 730

**Comment by migueesc123** [comment]
Does it work for you if you revert back to the previous version @klinejordan ?

**Comment by klinejordan** [comment]
@migueesc123 yes, when i revert back to the last pull request it works without issue.

**Comment by migueesc123** [comment]
could you please try the new project / mez file? @klinejordan  @ImkeF

**Comment by migueesc123** [comment]
Closing the issue as it appears to be working  for all users that have tested the new version of the connector
