### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by alexgbau** [migueesc123/PowerBIRESTAPI#22]
Hi team,

I'm really excited to try this but I'm not able to sign in. I continue to get the following error:

> Exception of type 'Microsoft.Mashup.Engine.Interface.ResourceAccessAuthorizationException' was thrown.

Any thoughts?

**Comment by migueesc123** [comment]
Hey!
When exactly are you getting this error ? 
Could you please share a screenshot ?

**Comment by klinejordan** [comment]
If you're trying to use the Admin end points, remember you have to be a Power BI Service Admin in order to make those API calls.

**Comment by alexgbau** [comment]
Thanks for the prompt replies.

Here is the screenshot:

**Comment by migueesc123** [comment]
when you click the Sign in option, are you able to get a new window to go through the authentication process at all?

**Comment by alexgbau** [comment]
Yes, I get a new window at login.windows.net/common/oauth2/authorize, select company account that is linked to Windows and then I get the error.

**Comment by ImkeF** [comment]
Getting the same error-message now. This morning it all worked fine.

**Comment by migueesc123** [comment]
seems to be working fine for me, but I'm not using the secret.

**Comment by migueesc123** [comment]
if you figure out what's the issue, please let me know! @ImkeF

**Comment by migueesc123** [comment]
Please try with the latest mez file and let me know how it goes. It should work.

**Comment by ImkeF** [comment]
Hi @migueesc123 ,
new file works beautifully now for me, thanks for that!
Just so say that it doesn't cover the secret. When adding "client_secret = client_secret," into row 753 the new code works fine for me as well (that's where the previous codes had trouble with).
But my app doesn't seem to require a secret, so my findings might not be representative.

**Comment by migueesc123** [comment]
Hey @alexgbau !
Could you please confirm that it works for you as well ?

**Comment by alexgbau** [comment]
Sorry, had a busy day. I will give this a try shortly.

**Comment by alexgbau** [comment]
All good now. Thanks!

**Comment by alexgbau** [comment]
Hi @migueesc123, the fix you applied has given me access to the connector and I can also access Personal Workspace and Workspace. I don't have any gateways so can't check that but I cannot access Functions or Power BI Service Administrator.

I have tried both Power BI Service Admin account and a Global Admin account but same error.

Example: 

Select Event Activity Log , enter 01/12/2019 in both Start and End Date, hit apply and get login prompt. Successfully login but then when I try to connect, get the following error:

![image](https://user-images.githubusercontent.com/59611693/71984886-af74b080-3264-11ea-8140-43973616f772.png)

**Comment by migueesc123** [comment]
Glad to hear that it's working now!

In regards to the error that you're getting, that's a tough one. That is most likely related to your permissions and the setup of your application.

I recommend that you check out the thread from issue #19 to get some suggestions on how to get to the bottom of it.
Unfortunately that's an issue that is not directly related to the Custom Connector, but the actual OAuth Application and permissions. What I can confirm is that the custom connector does require the Power BI Admin scope to be enabled at the application level so you can use those endpoints and your authenticated user must be a Power BI Admin.
Once you have those permissions correctly set, you should be able to use those parts of the connector without any issues.
