### ISSUE TITLE
Throttling issue

### ISSUE THREAD

**Issue by TheSQLGrrrl** [migueesc123/PowerBIRESTAPI#26]
Hello,

I am running a PBI report with your Custom connector successfully. But on a Premium tenant, It seems I am throttled and it fails. Frame show us this message
![image](https://user-images.githubusercontent.com/12843138/74513165-48ed4d00-4f0a-11ea-92df-98c43242deae.png)

Did you experience such issue ?

regards

**Comment by klinejordan** [comment]
Which API call were you using when you got this message?

**Comment by klinejordan** [comment]
@TheSQLGrrrl can you let me know which API call you were using when you got this error?

**Comment by migueesc123** [comment]
hey! @TheSQLGrrrl 
Are you still facing this issue with the API? Would you mind letting us know which function or call from the API is giving you this issue?

**Comment by migueesc123** [comment]
closing for no response
