### ISSUE TITLE
I get attached error when connecting to Power BI Service Administrator tables.

### ISSUE THREAD

**Issue by rhalabi** [migueesc123/PowerBIRESTAPI#27]
I get the attached error when I try to connect to any of the Power BI Service Administrator OR Functions tables.  I am successfully signed in and all other tables work fine when I click the connect button, but the Power BI Service Administrator OR Functions tables get the error when I click the connect button.

![Error](https://user-images.githubusercontent.com/53341216/74936289-7ffeab00-53af-11ea-9f82-6a6b2dae809d.jpg)

**Comment by migueesc123** [comment]
hey!
This appears to be related to the permissions that you have at your app level. 

I'd highly encourage you to take a look at the official documentation from Microsoft in regards to what permissions you need for those type of "Admin" calls.

The Custom Connector just handles the calls to the API, but the whole authentication and tokens are handled at your app level.
