### ISSUE TITLE
Power BI REST API Authentication failed

### ISSUE THREAD

**Issue by aakashpatel660** [migueesc123/PowerBIRESTAPI#29]
Hello 

I have followed the step which is provided but when I tried to load Power BI Service Administrator tables it gives an error saying we could not authenticate with credentials provided. Please try again. I have a Power BI administrator role assigned. Can someone please help. 
![Capture](https://user-images.githubusercontent.com/59940632/77546581-740c7a00-6e82-11ea-82d8-86dc1e17e1a9.PNG)

Thank you

**Comment by migueesc123** [comment]
Hey! I'd encourage you to check the other issues in this repo where this question has been addresses. Here's one of the possible solutions: https://github.com/migueesc123/PowerBIRESTAPI/issues/23#issuecomment-596712062

**Comment by chrisarys** [comment]
I had the same issue following the setup guideline.   I discovered that there is a new API permission called Tenant.Read.All that needs to be added and activated to the list in the API Permissions section of the app in the Azure portal.   The wizard to register an app for PowerBI does not include it, causing the error message "we couldn't authenticate with the credentials provided".  Hope this will help others :)

**Comment by klinejordan** [comment]
> I had the same issue following the setup guideline. I discovered that there is a new API permission called Tenant.Read.All that needs to be added and activated to the list in the API Permissions section of the app in the Azure portal. The wizard to register an app for PowerBI does not include it, causing the error message "we couldn't authenticate with the credentials provided". Hope this will help others :)

THANK YOU CHRISARYS!
