### ISSUE TITLE
WorkspacesList.Members do not have any data

### ISSUE THREAD

**Issue by hideakisuzuki007** [migueesc123/PowerBIRESTAPI#3]
Hi Miguel
Thanks for your help last time.  I have another question.
One of the tables I get through API is "WorkspacesList" and it has a  column named "Members" and it has no data, it is just blank. 

Is there any trick to get this data ?

Thanks in advance !
Hideaki

**Comment by hideakisuzuki007** [comment]
Hi Miguel
I found the issue, I just added "[value]" for the line that produces the users data and it works fine now, 
Here is the code 
      members = Table.AddColumn( DataTypes, "Members", each try Table.FromRecords( Json.Document(Web.Contents( "https://api.powerbi.com/v1.0/myorg/groups/" & [GroupID]&"/users") ) [value] ) otherwise null )

Maybe youu did it on purpose for not producing duplicate rows but anyways I thought I should share it with you in case you need it.

Regards
Hideaki

**Comment by migueesc123** [comment]
Hey Hideaki! 

Thanks for raising the issue and I'm happy that you were able to find a solution. Sorry for the late reply - just got back from the Microsoft Biz Apps Summit.
