### ISSUE TITLE
Problem with feature "Store datasets using enhanced metadata format"

### ISSUE THREAD

**Issue by stjeloma** [migueesc123/PowerBIRESTAPI#33]
When new feature "Store datasets using enhanced metadata format" is enabled the next error ocurred when "Close & Apply": 
<img width="400" alt="2020-04-24_9-10-14" src="https://user-images.githubusercontent.com/9448999/80184777-7d1c7280-860b-11ea-8d6a-8c63ea7aa11c.png">

**Comment by ImkeF** [comment]
Hi @stjeloma , there are still issues with this preview feature in Power BI. Strongly believe that those will be solved before this feature will be generally available. So it's probably best to wait enabling this feature until the bugs are solved.

**Comment by klinejordan** [comment]
I can no longer reproduce issues with enhanced metadata format
