### ISSUE TITLE
Issue with On-Premise Gateway

### ISSUE THREAD

**Issue by piterabrian** [migueesc123/PowerBIRESTAPI#34]
This custom connector is working great through the desktop.   I just installed the April release of the Gateway, and the gateway doesn't find the connector.

I've already checked that the gateway service account can access the folder it is in, and i have checked in the service that the gateway is enabled to use custom connectors.

Any ideas?

**Comment by migueesc123** [comment]
Hey!

Is the connector listed for you under the data gateway connectors tab? It should look like this:
![image](https://user-images.githubusercontent.com/9544580/81454441-e8109200-9151-11ea-9064-e8208d9281ed.png)
Unfortunately, we don't own the Gateway so we're unable to tell you more info about troubleshooting the gateway itself, but I can confirm that the connector is working as intended on my end.

You may want to post your issue on the official GitHub repo for the Microsoft Custom Connectors:
https://github.com/microsoft/DataConnectors/issues

the official Microsoft Power BI Community forum:
https://community.powerbi.com/

Create a ticket with the Power BI Support team or get in touch with your Microsoft Partner of choice to request further help in troubleshooting the gateway.
