### ISSUE TITLE
Standard-Mode Data Gateway

### ISSUE THREAD

**Issue by DMiradakis** [migueesc123/PowerBIRESTAPI#37]
@migueesc123 

I've got an issue I'd like to ask you about! I took a look at issue #34 , and I saw that in the screenshot that you provided, your gateway had **personal mode** in the parenthesis in the upper right-hand corner.

I, too, have an on-premises data gateway, only it's not a personal-mode gateway; it's what I believe Microsoft now calls the [**Standard Mode** on-premises data gateway](https://powerbi.microsoft.com/en-us/gateway/) which is installed on one of my company's servers.

That being said, I followed the same steps as the user that opened up issue #34 . However, my standard mode on-premises data gateway is unable to read the connector; it will not appear in the data gateway's Connector tab as an option, even though I have it pointed to the correct folder that contains the .mez file.

Power BI Desktop is installed on my personal laptop, and ,hence, I installed the custom connector according to the steps prescribed in your README - which works perfectly! My data gateway, since it is _not_ a personal mode data gateway but instead a standard mode data gateway, is installed on one of our servers and, therefore, does not have access to the C:\ folder that contains the .mez file _on my laptop._ However, the standard mode data gateway has access to a network drive/fileserver, and I can verify that it can access the .mez file in a folder on there. From the official [Microsoft documentation](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors), I don't get the impression that the data gateway has to have specific access to a _particular_ folder, but instead it just needs access to whatever folder the .mez file is in.

Have you had any issues or solutions in getting standard mode data gateways to read your custom connector? Is it designed only for personal mode data gateways?

Thanks for your time!

**Comment by DMiradakis** [comment]
@klinejordan 

Thanks so much for your speedy and highly informative response!

You are correct in regards to the OAuth2 authentication method requiring a gateway administrator. I have verified that I am indeed an admin for the gateway in question, and my coworker granted the gateway's default user account, [_NT SERVICE\PBIEgwService_](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors), access to the network folder containing the .mez file.

I have also verified that the "Allow user's custom connectors to refresh through this gateway cluster" box is checked in the gateway settings in the Power BI Service.

Additionally, I have only one machine for my clustered gateway service!

I hate to ask, but do you have any other ideas as to what could be preventing the gateway from seeing the .mez file? I'm going try again today; my coworkers and I restarted the gateway several times yesterday, but it didn't seem to help.

Thanks!

**Comment by klinejordan** [comment]
In the gateway configurator when you click on the connectors tab what do you see?

If the gateway can access the folder where the .mez file is located and you've set that folder as the location from which to load custom data connectors you should see this:
![image](https://user-images.githubusercontent.com/48561922/84405432-f45a9580-abbc-11ea-8a28-c310f8794422.png)

**Comment by DMiradakis** [comment]
Yeah I saw that same custom data connector table in the screenshot on the Microsoft documentation!

When my coworker and I tried yesterday, we saw the URL bar, and we _were_ able to point the gateway to the folder with the .mez file after that! But our issue is that the table above the URL bar in your screenshot never appeared for us, as if the gateway still couldn't read the .mez file.

I'm going to try again with my coworker today! Unfortunately, I can't get in and troubleshoot the gateway on demand due to our parent company's excessive security policies, but when I get the chance to check again, I'll let you know!

The only thing I can think of is that perhaps it took a while for the security permissions to set in for the gateway's default user account... we use Azure Active Directory across a multitude of servers, so I'm not sure if that had anything to do with it or not.

**Comment by DMiradakis** [comment]
Going back off of my previous comment, as I said, I can't login into the gateway on demand to troubleshoot it **or update it**. It just occurred to me that I saw a message yesterday when I got in that the gateway has newer versions available for update... and I am beginning to wonder if that could very well be an issue here.

Do you know if there is a minimum gateway version requirement for your custom connector?

**Comment by klinejordan** [comment]
I don't know that but if you're seeing the option to enable custom connectors for your gateway cluster I would expect it to work. 

Given you can't get PowerBIRESTAPI to appear in the list of custom data connectors I still think this is an issue of the service account not having access to the folder where the .mez file is located.

Can you try putting it somewhere in C:\Users\PBIEgwService?

**Comment by DMiradakis** [comment]
Great news! You can now close this ticket. The issue was something small and silly (of course). Whenever I would navigate to the network drive in the URL bar for the gateway, the URL that was generated was not fully qualified (it didn't have our \\fileserver\ address in it). Once I changed it manually to the fully-qualified location, the gateway picked up your custom extension immediately.

I'm going to put in a ticket on the Microsoft documentation page for this and ask them to note that if they are willing after I finish face palming.

Thanks so much for all of your help!
