### ISSUE TITLE
Gateway refresh issue

### ISSUE THREAD

**Issue by rhalabi** [migueesc123/PowerBIRESTAPI#38]
I have created a report using this custom connector in PBI desktop and everything works fine connecting as a Power BI Service admin application account.  I published report to web service and have setup a gateway connection for refreshing, but I get the error below. I have two gateway servers clustered together. I added custom connector on both gateway servers in connectors section and it shows up, I have allow custom connection gateway checkbox checked, but when refreshing I get error.  Any ideas?

![image](https://user-images.githubusercontent.com/53341216/85601644-300d4a80-b614-11ea-83bd-9659b8461287.png)

**Comment by migueesc123** [comment]
it appears to be related to the authenticated user used for the call to the table that you have named "Capacity_Dashboards". Could it be that the authenticated user on the gateway isn't the correct one? have you tried clearing those credentials and using a new one?

**Comment by rhalabi** [comment]
> it appears to be related to the authenticated user used for the call to the table that you have named "Capacity_Dashboards". Could it be that the authenticated user on the gateway isn't the correct one? have you tried clearing those credentials and using a new one?

Thx for the reply. You mean on the gateway connection? How do I clear the credential and re-create?

**Comment by migueesc123** [comment]
Correct. On the gateway connection. 
Other than that, you might need to do more troubleshooting to see why the authenticated user doesn't have access to that endpoint.
At the Custom Connector level we don't really handle anything related to permissions. This is handled by the API and your webapp. The error raised is simply the direct response from the API for the call made by the authenticated user.

**Comment by klinejordan** [comment]
For custom connectors using OAuth authentication, the user's credentials must be a gateway admin. See the considerations and limitations: https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors#considerations-and-limitations 

So if you're using a service account, that account must also be an admin on the gateway.
