### ISSUE TITLE
Unable to access data from Functions: Event Activity Log

### ISSUE THREAD

**Issue by sau6402** [migueesc123/PowerBIRESTAPI#40]
Hi Team,

I followed the instructions mentioned.

I have the Power BI Service Admin role assigned to me.
Using those credentials, I created the native app followed it up with the azure portal steps and successfully created the Custom Connector.
Once I am connected using PBI Desktop, I get a list of options like Functions, Gateways, etc ... but strangely when try the Event Activity Log, it gives a popup to login again and then says "We couldn't authenticate with the credentials..."(Image attached).
I am sure they are typed in correct as I am able to login with it everywhere else.
![error](https://user-images.githubusercontent.com/762849/86000210-dd27fe80-ba2a-11ea-931a-d313f697f418.JPG)

I am primarily only interested in Event Activity Log.

Please guide.

--
Regards
Saurabha J

**Comment by migueesc123** [comment]
Hey!
This error is provided by your web application. You might need to check the documentation and your specific setup to see which permission you’re missing in your web app.
Maybe it has to do with the one mentioned in issue #29

**Comment by klinejordan** [comment]
Do you get the same error when using other end points besides the activity event log?

**Comment by sau6402** [comment]
Hi klinejordan,

If I am using a non PBI Service Admin login, then I am able to access everything except the functions and Admin part.
If I am using the PBI Service Admin login, then I cannot access anything.

The screenshot I have attached in the question appears when trying to use the Event Activity Log under Functions.

@migueesc123  - I looked at the link provided by you. It seems the tenent.readAll permission is not granted to the app. But since I have created the app using Poser BI Service Admin Account, I should be able to grant it access but that button "Grant Admin consent for ...." is disabled. 
PFA permissions screenshot.
![permissions](https://user-images.githubusercontent.com/762849/86086814-4148d200-bac0-11ea-9985-777ee817e1ab.JPG)
Please guide.

--
Regards
Saurabha

**Comment by migueesc123** [comment]
@sau6402 if that button is disabled, then that's the culprit and you'll need to find a fix for that. Here's a number of threads that talk about this:
#25 
https://github.com/migueesc123/PowerBIRESTAPI/issues/23#issuecomment-596712062
 https://github.com/migueesc123/PowerBIRESTAPI/issues/19#issuecomment-561359108

Closing as this is outside the scope of the custom connector capabilities and specific to a Web Application authentication / consents of a specific tenant.

**Comment by sau6402** [comment]
Thanks @migueesc123 for your quick response !!!
