### ISSUE TITLE
Implementing Incremental Refresh

### ISSUE THREAD

**Issue by sau6402** [migueesc123/PowerBIRESTAPI#41]
Hi Team,

I followed the tutorial and have been able to fetch activity logs data successfully.
Thanks to your custom connector !!!

I am now planning to have an incremental refresh setup. I read on your blog that it is possible.
But somehow I am unable to figure it out.

This is my M Code code till now:
```
let
    Source = PowerBIRESTAPI.Navigation(),
    Functions = Source{[Key="Functions"]}[Data],
    EventActivityLog = Functions{[Key="EventActivityLog"]}[Data],
    invoke_function = EventActivityLog(#date(2020, 7, 1), #date(2020, 7, 9)),
    add_dttm = Table.AddColumn(invoke_function, "Activity Date", each DateTime.From(
	Text.Combine(
		{Text.Range([CreationTime],0,10),
		Text.Range([CreationTime],11)}, " "
	)
) + #duration(0,5,30,0)),
    #"Changed Type" = Table.TransformColumnTypes(add_dttm,{{"Activity Date", type datetime}})
in
    #"Changed Type"
```

What I have done above is to get data from 1st July till date and then converted date to IST.

I have created the **RangeStart** and **RangEnd** Parameters, but unable to understand how to implement them.
Please guide.

--
Regards
Saurabha J

**Comment by migueesc123** [comment]
Hey!
You can read more about how to implement Incremental refresh from the following post:
https://www.poweredsolutions.co/2018/05/08/first-thoughts-on-power-bi-incremental-refresh/

if you need further help setting up the incremental refresh to your specific needs, you can get in touch with me and my team over email (info@poweredsolutions.co) for a quote on our consultancy services.

**Comment by sau6402** [comment]
@migueesc123 ,

I have used Incremental refresh for multiple of my reports previously.

But I am unable to understand how to call the REST API function using that.
If you could help/guide me with that in the above M-Query that would be helpful.

--
Regards
Saurabha J

**Comment by migueesc123** [comment]
@sau6402 the article that I mentioned in my previous reply explains it on a step by step basis and even using a Power BI Custom Connector that I created with almost the same design that this one has for a function.
The scope of the support for this repo is specific to the functionality within the Power BI Custom Connector. 

Again, if you're looking for help with any custom requirement or anything outside of the scope of this repo, you can contact me and my team at info@poweredsolutions.co for a quote on our services. I can guarantee that we can help you with anything related to Power BI such as creating a specific Incremental refresh policy that can be used against the Event Activity log function.
