### ISSUE TITLE
API not showing in Home\Get Data

### ISSUE THREAD

**Issue by Anderson681** [migueesc123/PowerBIRESTAPI#42]
First of all, sorry for my english.

I placed the **Power BI API.mez** in my C:\Users\W81\Documents\Power BI Desktop\Custom Connectors, but i still can not find it in the Common Data Sources. I've already allowed any data extensions in Options\Global\Securities.

I've a connector (.mez) that works with Neo4j, so i think Power BI Desktop is correctly configured.

![Data extensions](https://user-images.githubusercontent.com/26250577/87966462-ae360300-ca93-11ea-923f-d52649e882c3.png)
![local file](https://user-images.githubusercontent.com/26250577/87966469-af673000-ca93-11ea-9f3e-6d09baa956fd.png)
![Common data connectors](https://user-images.githubusercontent.com/26250577/87966470-af673000-ca93-11ea-96fb-4187f2670e04.png)

**Comment by migueesc123** [comment]
Hey!
I wouldn't be able to tell you what might be going on without taking a deep look into it, but I'd highly encourage you to follow all the steps from our readme file and try to replicate this issue on a different computer. I've only seen this happen when the steps found in the readme doc were not followed causing the connector to not load whatsoever.

I can confirm that the connector is working as intended, but if you happen to replicate the issue on a different computer, please reply to this thread with the step by step on how to replicate the issue.

**Comment by Anderson681** [comment]
It is solved, but i really don't know what did i do.

I replicated this issue in a different computer, but i realized the problem didn't happen with files AppID.txt and ClientSecret.txt filled in blank. I just replaced them in Custtom Connectors folder and it works.

Thanks a lot for your attention and sorry for waste your time.
