### ISSUE TITLE
Great idea !! But having some issues

### ISSUE THREAD

**Issue by TheResearcher-Hub** [migueesc123/PowerBIRESTAPI#43]
![powerbi errors](https://user-images.githubusercontent.com/54586718/88594703-e94dae80-d01e-11ea-98d5-d9c1e117db6f.png)

When loading the data 
![image](https://user-images.githubusercontent.com/54586718/88596227-dab4c680-d021-11ea-9140-924115c7085d.png)

I am getting errors loading this data (see screenshots) 

Gateway Data Source users
Failed to save modifications to the server. Error returned" 'OLE DC ot ODBC Error: [Expression.error] The field 'datasourceid' of the record wasnt found

**Comment by klinejordan** [comment]
Are you an admin a gateway? And do you have any active data sources on that gateway?

What do you see in the Power BI service when you go to settings>manage gateways?

**Comment by migueesc123** [comment]
Hey!
Let's pinpoint the issues. Which queries are giving you the errors? Please give us the steps to repro.

**Comment by klinejordan** [comment]
There's no field called datasourceId in the Gateway Data Source Users call - its likely coming from another query. Can you try adding the blow one by one to isolate which query is throwing that error? 

Workspaces->Datasources
Workspaces->Dataflows

**Comment by migueesc123** [comment]
> When loading the data
> ![image](https://user-images.githubusercontent.com/54586718/88596227-dab4c680-d021-11ea-9140-924115c7085d.png)
> 

I'm not entirely sure why you're getting this Navigator experience. That's not how our Custom Connector looks like, right @klinejordan ?

**Comment by TheResearcher-Hub** [comment]
I am pretty new to PowerBi, will do my best. I edit the txt files as per the instructions. 
I launch PowerBi, GetData, search for API and it shows PowerBIRESTAPI.NAVIGATION (Beta), connect, it connects to the data and under Admin3 i see data with no issues. Under appworkspace and below I get all errors as shown by the earlier screenshot. 
![image](https://user-images.githubusercontent.com/54586718/88596597-a392e500-d022-11ea-9724-7a838dec9cb3.png)

**Comment by migueesc123** [comment]
that doesn't look like the experience that you should be getting from our connector.  I wouldn't be able to even guess how you're getting that experience, but the one that you're looking for (as far as the Navigator window) is the one that we have in our Readme file.
https://github.com/migueesc123/PowerBIRESTAPI

Maybe you've edited a piece of code that shouldn't be edited? or zipped the file incorrectly?

**Comment by klinejordan** [comment]
No its not how it should look - my guess is the file was re-zipped incorrectly, maybe by excluding the .resx files

**Comment by TheResearcher-Hub** [comment]
I used Windows explorer to Zip the file.. 
I took the mez file, renamed it to .zip, went to the folder and edited the text files with the proper info, then used explorer to sent to compressed zip and then renamed it back to the mez file.

**Comment by migueesc123** [comment]
> I used Windows explorer to Zip the file..
> I took the mez file, renamed it to .zip, went to the folder and edited the text files with the proper info, then used explorer to sent to compressed zip and then renamed it back to the mez file.

it could be what @klinejordan says. I'd recommend that you try doing the process again and download the .mez file again. I just did and I'm not getting that issue.

**Comment by TheResearcher-Hub** [comment]
After GetData, what is the name of the connector i should search for? I will try again..

**Comment by klinejordan** [comment]
it should show up as Power BI API

![image](https://user-images.githubusercontent.com/48561922/88598431-206f9000-d01e-11ea-8112-26cf54c57d66.png)

**Comment by TheResearcher-Hub** [comment]
Figured out how to make it appear under Power Platform, i was zipping at a folder level and it created a subfolder. Highlighted all the files and zipped it, moved it to the proper folder and now it appears as expected. 

It pops u a Login request and i use the account that I am a PowerBiadmin, i get the MFA request back to verify and then the following error. I have no other credentials local or global.. I have closed down PowerBi and reopened it with the mez file in the custom connector.. 
![image](https://user-images.githubusercontent.com/54586718/88599526-35055580-d029-11ea-93aa-910503735b5c.png)

Exception of type 'Microsoft.Mashup.Engine.Interface.ResourceAccessAuthorizationException' was thrown.

I do greatly apologize for my issues, thank you for answering my questions.

**Comment by klinejordan** [comment]
Glad you got that part working - that new message indicates your app registration doesn't have the correct permissions. Please review Section 1 of the read me to understand what permissions must be delegated to the service principal to use this custom connector.

**Comment by TheResearcher-Hub** [comment]
Ensured that all permissions are there and thought it could be my secret so I deleted the old one and created a new one. After loading the Connector it asks me to login and I use the Power BI Admin account, I login with MFA successfully. I see a list, The (Admin) works fine but all the other fields throw errors

Permissions: 
![image](https://user-images.githubusercontent.com/54586718/88601664-72b8ad00-d02e-11ea-9af7-7668dd2186c5.png)
List:
![image](https://user-images.githubusercontent.com/54586718/88601680-7b10e800-d02e-11ea-8480-15f4477d27e9.png)

Error again:
![image](https://user-images.githubusercontent.com/54586718/88601761-911ea880-d02e-11ea-86f2-29bc4e20642a.png)

**Comment by TheResearcher-Hub** [comment]
I think it has to do with the user ID i login as, I have to use 2 different accounts, the PowerBI admin account and a non admin account. 
If you are willing to, perhaps i could share my screen and go through this in Teams??

**Comment by migueesc123** [comment]
Hey @TheResearcher-Hub ! 

Unfortunately the topic of how your Web App is set up specifically for your organization is something that falls out of the scope of the support that we provide through this repo. 

Here's a number of threads that could help you with it:
#25 
https://github.com/migueesc123/PowerBIRESTAPI/issues/23#issuecomment-596712062
 https://github.com/migueesc123/PowerBIRESTAPI/issues/19#issuecomment-561359108

My company (Powered Solutions) provides support on this and other Power BI Custom Connectors via Teams. Should you require help setting up the connector or customizing the connector, we can absolutely help you. Contact us at info@poweredsolutions.co and we'll send your way a quote for our services.

**Comment by TheResearcher-Hub** [comment]
Just an update, because of the way our company does its security, access to some of the data requires me to use 2 different accounts to get the data. I was able to get the ADMIN data using 1 account and the rest of the data using another.. Separate. 
I was able to see ALL the data using 2 different accounts, i just switched them in the report but i was not able to see all the data at once with 1 account.. Confusing for sure.. :-)

**Comment by ptyx507** [comment]
It's usually a case by case scenario figuring out the configuration for every single company. As mentioned, this is something that goes out of the scope of the support that we provide on this repo, but I'm glad to know that you were able to find a solution.

Hope you enjoy our custom connector and best of luck!
