### ISSUE TITLE
Error messages on Azure App Registration

### ISSUE THREAD

**Issue by hawkerr1** [migueesc123/PowerBIRESTAPI#46]
Hi
[Rest API screenshot.docx](https://github.com/migueesc123/PowerBIRESTAPI/files/5566867/Rest.API.screenshot.docx)
 Miguel,
Firstly, a big thank for the connector. I've used it to great effect in a project we are doing to move content from one Power BI Tenant to another.  It was great to create an inventory of everything in the source tenant and then determine what needed to be moved.

I've just asked the admin of the new tenant to register the app there, so that we can use your API again.  They reported a couple of error messages when registering.  One was about the app using a deprecated version of the Azure Graph API and the other was about verified publishers. I'm attaching a screenshot.  I wondered if a new version of this is going to resolve these issues or if you know of another similar connector which won't have these issues.

Again thank you so much for your hard work. 
Rob

**Comment by migueesc123** [comment]
Hey Rob!

None of the warnings shown in your file are related to the custom connector itself, but rather the specific configuration of your application. You could remove the graph api delegation that you have as that component is not needed for this custom connector. 
The other warning is also specific to your app and I’d encourage your admin to configure the app to your needs. The only components that the connector needs are just the ones to the power BI rest api.

I’m not aware of any other custom connector similar to this one, but if you find any please let me know.

Best!

**Comment by hawkerr1** [comment]
Thanks Miguel. I'm showing off my lack of knowledge of Azure app registration here :).
Appreciate the help and I will talk to our Admin about this.
I also think your connector is unique from my research so far.  Thanks for your awesome contribution to the community deserving of the MVP award on its own!
Thanks,
Rob
