### ISSUE TITLE
Microsoft.Mashup.Engine.Interface.UnpermittedResourceAccessException, 

### ISSUE THREAD

**Issue by klabir** [migueesc123/PowerBIRESTAPI#47]
Hello
in a test tenant, i get this error. in an aother all work fine. any idea whyt coudl be differet? thx klaus
d7e40a9d3ce9","message":"","httpStatusCode":"OK","exceptionType":"","errorCode":"","errorDetails":"","cloudName":"GlobalCloud","parentId":" ffffffffffffffff","isError":"False","sessionId":"ffffffffffffffffff","deviceId":"fffffff","userId":"ffffffffffffffffffff","isInternal":"False","authenticatedUserId":"Unknown","ProductVersion":"2.85.681.0 (20.09)","ActivityId":"fffffffffff","Process":"PBIDesktop","Pid":5728,"Tid":5,"Duration":"00:00:46.3711815"}
DataMashup.Trace Information: 24579 : {"Start":"2020-11-20T14:43:40.9607477Z","Action":"SharedLocalStorageAccessor/AcquireMutex","ProductVersion":"2.85.681.0 (20.09)","ActivityId":"ffffffffffffffffffffffffffffffffff0","Process":"PBIDesktop","Pid":5728,"Tid":5,"Duration":"00:00:00.0000093"}
DataMashup.Trace Information: 24579 : {"Start":"2020-11-20T14:43:40.9674904Z","Action":"PBI.TraceMessage","sessionId":"ffffffffffffffffffffff","deviceId":"9d190bbf","userId":"fffffffffffffffff7ad","isInternal":"False","authenticatedUserId":"Unknown","Message":"AuthenticationManager.TryGetUserIdentityInfo: Valid stored client access from FrontEndUrl = https://app.powerbi.com/ for TenantId = ffffffffffffffff00","ProductVersion":"2.85.681.0 (20.09)","ActivityId":"ffffffffffffffffffffffff000","Process":"PBIDesktop","Pid":5728,"Tid":5,"Duration":"00:00:00.0000199"}
DataMashup.Trace Information: 24579 : {"Start":"2020-11-20T14:43:40.9717980Z","Action":"PBI.TraceMessage","sessionId":"effffffffffffffffffffffffffa8b","deviceId":"9d190bbf","userId":"fffffffffffffffffffd","isInternal":"False","authenticatedUserId":"Unknown","Message":"AuthenticationManager.AcquireTokenAsync: Acquiring token using TokenCache","ProductVersion":"2.85.681.0 (20.09)","ActivityId":"fffffffffffffffff000","Process":"PBIDesktop","Pid":5728,"Tid":5,"Duration":"00:00:00.0000118"}
DataMashup.Trace Information: 24579 : {"Start":"2020-11-20T14:43:40.9779288Z","Action":"PBI.MsalLog","Message":"Info: (False) MSAL 4.16.0.0 MSAL.Desktop Microsoft Windows NT 10.0.17763.0 [11/20/2020 14:43:40 - ffffffffffffffffff2] MSAL MSAL.Desktop with assembly version '4.16.0.0'. CorrelationId(fffffffffffffffffff8a12)","ProductVersion":"2.85.681.0 (20.09)","ActivityId":"000ffffffffffffff000000","Process":"PBIDesktop","Pid":5728,"Tid":5,"Duration":"00:00:00.0000555"}
![bug](https://user-images.githubusercontent.com/45362306/99939643-d0ee6600-2d6a-11eb-96ca-bdfc7d78825d.jpg)

**Comment by migueesc123** [comment]
hey!
This is related to your application configuration and not the custom connector itself. I'd encourage you to get in touch with your Azure Active Directory Admin to check how that webapp has been setup and if it does indeed have the permissions to make the calls to the Power BI REST API.

Your admin will have to perform some debugging to see why the token can not be acquired and what sort of error your own application is providing.

_**Note:** If your tenant is in the gcc cloud then that might be a different scenario that uses a different set of endpoints even for the resourceUrl. This custom connector hasn't been tested for the gcc cloud or any oher sort of private cloud._

**Comment by klabir** [comment]
thx, i will check it.
