### ISSUE TITLE
Add Dashboard/Report Usage to this connector

### ISSUE THREAD

**Issue by VictorMMM** [migueesc123/PowerBIRESTAPI#5]
I have an idea for growing this brilliant connector: adding the dashboard/report usage to it (they are stored in a small cube for each of the objects, created automatically by the tenant). Not sure if this is possible or how to do it via API, but it would be neat to get it the same way.

Thanks, 
Victor

**Comment by migueesc123** [comment]
Hey! 

I spoke with the Power BI Team in 2018 and back now in 2019 during the Business Applications Summit and they should be creating something that overlaps with this custom connector, so all the development has been put on hold for this. It would be great if you could raise this to Microsoft and tell them that they should have a certified Custom Connector for their REST API.
You could try twitter or one of their social media accounts.
