### ISSUE TITLE
Getting "We couldn't find the file AppID.txt" error

### ISSUE THREAD

**Issue by arubalak** [migueesc123/PowerBIRESTAPI#50]
When I click on sign in button after opening the custom connector getting "We couldn't find the file AppID.txt" error. Followed the document and do have the file in there.
![AppID_Error](https://user-images.githubusercontent.com/76234871/102677991-42e38080-415a-11eb-9b91-647c67bde57a.PNG)

**Comment by migueesc123** [comment]
Hey

Could you share a screenshot that shows the contents or your .mez file, please ?

what could’ve happened is that when you did the zip again you didn’t add that file and it got left behind.

**Comment by arubalak** [comment]
Hi Miguel,

Thanks for your response. I do see the file in there.

[image: image.png]
Thanks
Arun

**Comment by migueesc123** [comment]
@arubalak I do not see the image. Could you please post it again, please?

**Comment by arubalak** [comment]
> @arubalak I do not see the image. Could you please post it again, please?

![AppID_Error_SC](https://user-images.githubusercontent.com/76234871/102707724-56721280-4252-11eb-88d9-864db19ab4ea.PNG)
There you go

**Comment by migueesc123** [comment]
Good! You do have the file. 

Now, could you please open the AppID.txt and show me a screenshot with the last 6 characters?

**Comment by arubalak** [comment]
Here is the screenshot
![AppID_Error_SC1](https://user-images.githubusercontent.com/76234871/102805132-a09ce600-436f-11eb-9e50-b49231ebbe07.PNG)

**Comment by migueesc123** [comment]
Is the "Hidden" part actually in the file? or did you write that just to protect the appID number? @arubalak

**Comment by arubalak** [comment]
I just wrote it to protect the appID :)

**Comment by migueesc123** [comment]
@arubalak  I'm not entirely sure what could be wrong here, but I'm unable to repro this situation. Could you try following the steps on a different computer and see if you can repro the issue?

If you can, could you please post the exact step by step of what you're doing in order for us to repro the issue?

**Comment by arubalak** [comment]
Tried it on a different machine and it worked. Thanks for your help. 
With your code there is no limit of 5000 or 10000 rows like the API limitation right?

**Comment by migueesc123** [comment]
The only limitations are imposed at the data source. There are no limitations made inside the custom connector.
