### ISSUE TITLE
Why wont OAuth work with Dataflows?

### ISSUE THREAD

**Issue by mitchonfire** [migueesc123/PowerBIRESTAPI#51]
Thanks for this connector it is awesome!
The connector works with datasets from power bi desktop and as a custom connector on gateways for refreshing the dataset when published to the service.

However, when the power query's are migrated to dataflow entities, the connector is detected on the specified gateway, but an error is thrown when you try configure "how to connect" with your organisational account.

**Comment by klinejordan** [comment]
Custom connectors are not yet supported for dataflows unfortunately
