### ISSUE TITLE
Newest .mez file

### ISSUE THREAD

**Issue by rhalabi** [migueesc123/PowerBIRESTAPI#54]
Is the AppID.txt and ClientSecret.txt no longer needed or used in the newest .mez file?  I don't see them when converting to .zip and extracting.  The reason I am asking is because a long time working .pbix is now failing with the attached error and not sure why.  I was going to see if newer mez file fixes report.  Any ideas on the error or do I need to use newer .mez?

![image](https://user-images.githubusercontent.com/53341216/114608343-3502bf80-9c63-11eb-815c-98b765884c25.png)

**Comment by migueesc123** [comment]
Hey!
Neither one of those files is needed anymore. The function "MetricsDataConnector.GetMetricsData" is not part of this custom connector. Could it be an issue related a different connector. Can you confirm?

**Comment by rhalabi** [comment]
Thx, yes it is related to another issue. Thx for the response and updating .mez to not need files anymore.
