### ISSUE TITLE
Accessing Pro workspaces with this connector

### ISSUE THREAD

**Issue by HakeemOlajuwon** [migueesc123/PowerBIRESTAPI#64]
Hi!

Can I use this connector to view refresh histories if I only have a pro account and want to view a pro workspace?

When I select the "refresh history" query under the "Workspaces" folder I get the error message "Expression.Error: Access to the resource is forbidden."

**Comment by migueesc123** [comment]
You should be able to - I just tested this and it appears to be working as intended. 

You may want to contact your Power BI admin to check the error and trace it through another tool such as Fiddler to see exactly what error code you're getting from the REST API. The  "resourrce is forbidden" means that you do not have the access to such resource and this is not imposed by the custom connector.
