### ISSUE TITLE
Endorsement details and Sensitivity Label not available

### ISSUE THREAD

**Issue by evnpresson** [migueesc123/PowerBIRESTAPI#65]
The new endorsement details and sensitivity labels for reports are not available via the connector per the Microsoft documentation:
https://docs.microsoft.com/en-us/rest/api/power-bi/reports/getreports

**Comment by klinejordan** [comment]
I've added the enhancement tag to this as these fields are relatively new to the API. You can always use the GETData function to return the raw JSON and parse it yourself or you are more than welcome to submit a PR to this repository if you'd like to add it to the connector.

**Comment by klinejordan** [comment]
I have a ticket with Microsoft support as these arrays are not showing up in the expected API calls for reports, datasets and dataflows.

**Comment by klinejordan** [comment]
> I have a ticket with Microsoft support as these arrays are not showing up in the expected API calls for reports, datasets and dataflows.

I'm told this is by design and the Scanner APIs (which are not available in this custom connector) is the only place to get Endorsement Details right now.
