### ISSUE TITLE
Re-Open: New mez: Authentication AAD 

### ISSUE THREAD

**Issue by shruthiMoti** [migueesc123/PowerBIRESTAPI#67]
Hi,

After the Authntication is changed to AAD.
I am getting below error:
The application 'Microsoft Power Query for Excel' asked for scope 'user_impersonation' that doesn't exist on the resource.

Is it possible to set any other scope. oauth2Permissions in my APP does not have value to be 'user_impersonation'

When you said "That’s pretty odd. The AAD authentication uses a first party application directly from Microsoft. We don’t own that application and the whole flow has been setup by Microsoft. The only thing that the connector does is define what resourceUrl we need the permissions to in order to query the Power BI REST API.".

Is the setting only for resourceUri = "https://analysis.windows.net/powerbi/api"; or can it be applied to others as well.
I am trying to use my own API as resource.

Thanks in Advance,
Shruthi

**Comment by migueesc123** [comment]
closing as this was answered on #66
