### ISSUE TITLE
AuthorizationException

### ISSUE THREAD

**Issue by SergiyVV** [migueesc123/PowerBIRESTAPI#7]
Hi Miguel,

I followed your instuctions.
- Changed Application Id
- specified Redirect URL as https://oauth.powerbi.com/views/oauthredirect.html
- API permissions for reading were granted.

The issue is each time in Power BI Desktop when I connect using your connector and provide valid login/password I get the following message of error:
_Exception of type
'Microsoft.Mashup.Engine.Interface.ResourceAccessAuthorizationException' was thrown._

I recreated an App but failed to succeed.
What am I doing wrong?

![Screens](https://user-images.githubusercontent.com/52447998/60500840-aefeca00-9cc3-11e9-850f-886156f235db.png)

**Comment by migueesc123** [comment]
Hey! I wish that I could tell you what's going on, but it really depends on what type of response you're getting. Could it be a 403 response? Not sure. The investigation would need to happen with your credentials.
What I can share with you is how the app looks on my end:
![image](https://user-images.githubusercontent.com/9544580/60512746-12c0cd00-9c9b-11e9-8087-3d22997109d8.png)
and I can confirm that the Custom Connector is working correctly for me

**Comment by stjeloma** [comment]
I have a the same problem: Microsoft.Mashup.Engine.Interface.ResourceAccessAuthorizationException, any solution Miguel?

**Comment by migueesc123** [comment]
@stjeloma  I think that you'd need to check what response header code you're getting from the API. I'm not being able to repro this error and I have some customers who are using it right now without any issues. The ResourceAccess error is related to an error at the authentication level, but the best way to see the actual response from the API is by using something like Fiddler to figure out what error message the actual API gives you and not Power Query.

**Comment by SergiyVV** [comment]
@migueesc123,
Fiddler shows the following
![fiddler](https://user-images.githubusercontent.com/52447998/61671279-98122d00-acef-11e9-994d-427c9623b275.png)

**Comment by migueesc123** [comment]
that doesn't appear to be the call that handles the authentication, but one that handles a javascript from the OAuth 2.0 flow. Usually the response code that you're looking for is a 401 code for the authorization error that you're looking for.
This could be a situation with how you've set up the App - this is most likely the cause. I recommend that you try to have your App exactly as shown in the previous screenshot that I shared. Again, I can confirm that this is working correctly on my end and that the Custom Connector is working properly.

**Comment by SergiyVV** [comment]
I generated a client secret for my App, then I modified TokenMethod function adding the client secret to the query string. Rebuit the project.
That did the trick.
![PBI_Connector](https://user-images.githubusercontent.com/52447998/63227891-42e51080-c1f4-11e9-9e78-4fa589d4ea53.png)
