### ISSUE TITLE
Gateway APIs not working - missing column 'id' 

### ISSUE THREAD

**Issue by eziam-l** [migueesc123/PowerBIRESTAPI#72]
![Gateway-missing colum](https://user-images.githubusercontent.com/63868694/129771239-09c11072-68f0-436d-ac5a-379202f502aa.png)

**Comment by klinejordan** [comment]
Are you a gateway administrator on at least one non personal gateway in your tenant?

**Comment by eziam-l** [comment]
@klinejordan that was the issue.
It works only for gateways I am admin of.

I was thinking PBI admin accounts would be able to see all gateways in the tenant.

**Comment by klinejordan** [comment]
Yes, PBI admin accounts only work for the APIs in the Power BI Service Administrator folder because the Gateway APIs themselves explicitly require the use to have the gateway administrator role - PBI Service Administrator is (strangely) not enough.

**Comment by Chris-Burgess-ACTGOV** [comment]
Hey Guys
vote for this - [
get gateways as admin - REST API using Service Principal](https://ideas.powerbi.com/ideas/idea/?ideaid=19dcb39f-01de-eb11-ba5e-281878bd2252)  - trying to get Admin access to the Gateway data :)
