### ISSUE TITLE
Add Dataset-Dataflow Links

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#73]
Can these be added? Requires use of https://api.powerbi.com/v1.0/myorg/groups/{{groupId}}/datasets/upstreamDataflows. This helps in being able to identify linkage between dataflows and what datasets that are used in.

**Comment by migueesc123** [comment]
@relax528 Could you share a link to the documentation of that endpoint, please?

**Comment by relax528** [comment]
It would be these two:
https://docs.microsoft.com/en-us/rest/api/power-bi/dataflows/get-upstream-dataflows-in-group
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/get-dataset-to-dataflows-links-in-group

Quick question - What users permissions are required to get the Power BI Event Activity. Do they need to be a Microsoft 365 Global or Power BI admin? I see you can specify dates, but not which event, does it get them all?

Thanks

**Comment by migueesc123** [comment]
thx for the info. I'll let @ImkeF and @klinejordan handle the feature request.

in terms of the activity log, you can find the article to their documentation below:
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing#activity-log-requirements

It basically gets all the events within the given time period.

HTH!

**Comment by klinejordan** [comment]
We'll keep it on the backlog to expose the dataflow lineage APIs but can't promise a date. 

For the Activity Log API you need to have Global Admin or Power BI Admin roles assigned. You can really only filter by start and end date in UTC, not a specific activity.

**Comment by klinejordan** [comment]
I opened up the hood and added these as they were pretty easy. Thanks!
