### ISSUE TITLE
Add workspace Group to Workspaces

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#74]
Could workspace type (group or workspace) be included in the workspaces list, I need to be able to filter out the old classic workspaces created from Office 365 groups. 

{
      "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "isReadOnly": false,
      "isOnDedicatedCapacity": false,
      "type": "Group",
      "name": "xxxxxxxxxxxxxxxxxxxxxx"
    }

**Comment by klinejordan** [comment]
I've added this field to the Workspaces query in the Workspaces folder
