### ISSUE TITLE
Possible Truncation of Error Description in Refresh History

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#80]
Possible issue with the custom connector, the error description in dataset refreshes seems to get truncated and does not contain full json data. I need to parse the error for the embedded content. Calling the dataset refreshes method of the REST API appears to return full json data. 
Thanks!

**Comment by klinejordan** [comment]
@relax528 can you provide more information, including screenshots, reproduction steps and examples?

**Comment by migueesc123** [comment]
Closing. Will re-open once we receive further info about the possible issue from @relax528
