### ISSUE TITLE
Get Data with {report id}

### ISSUE THREAD

**Issue by detrickm** [migueesc123/PowerBIRESTAPI#86]
How can I get a listing of all users for **all** report ids using the following API?
https://api.powerbi.com/v1.0/myorg/admin/reports/{reportId}/users

I would like to gather this listing **without** providing a report id in the parameter to run for **all** report id?  

Similar to how the Workspaces Users is working in the connector using the https://api.powerbi.com/v1.0/myorg/groups/{groupId}/users

**Comment by migueesc123** [comment]
Just checked the code for the connector and I don't see a query for that specific endpoint. You could first use one of the other tables to get the "ReportIDs" and then run the GetData function against those IDs.

I'm leaving this one open in case @ImkeF  or @klinejordan  have any other comments, suggestions or would like to add that functionality to the connector.

**Comment by klinejordan** [comment]
This (and the GetDatasetUsersAsAdmin, GetDataflowsUsersAsAdmin, GetDashboardUsersAsAdmin, etc) are brand new API that's still in preview - they came out on 9/10. 

I haven't evaluated its performance at all and would be extremely surprised if it performed well in large tenants given the size of the payload that'll come back and the 200 calls per hour limitation they have. This should be treated as an enhancement request but like I said this is probably going to behave like the GetDatasetDatasourcesAsAdmin API - slowly.

**Comment by detrickm** [comment]
Thanks @migueesc123 I was able to create a table with the ReportIDs but i was not quite sure how to input it in the GetData function to produce a table for all ReportIDs.  Do you have any recommendations or examples as to how i could input this?

**Comment by migueesc123** [comment]
assuming that you have the column that has the IDs, something like:
`FunctionName("admin/reports/"&[ID Column] &"/users")`

should do the trick

**Comment by migueesc123** [comment]
Forgot to mention that the function itself (GetData) does provide an example and some documentation on how it works. Just in case, that function is in the "Functions" folder.

**Comment by detrickm** [comment]
Thanks again @migueesc123 and @klinejordan for your very fast responses!

**Comment by cool-Blue** [comment]
@migueesc123 tank you for this!  Sorry for the dumb question: where is the "Functions" folder?

**Comment by migueesc123** [comment]
> @migueesc123 tank you for this! Sorry for the dumb question: where is the "Functions" folder?

You should be able to see it in the navigator window. There should be a little folder icon with the name "Functions". You can also see a screenshot of how the navigator looks like in the main page of this repo.

**Comment by cool-Blue** [comment]
> 

Thanks @migueesc123, I missunderstood.  I saw the example in the function metadata but, was looking for more info.  I thought you meant there was more detailed documentation somewhere (here in the repo for example).  I will try to read the code. All good!

**Comment by Krishna1805** [comment]
@cool-Blue Could you please share the details how did you figured it out.
I have the Report ID's in one table and how would I apply these ID's on the below API to get the users of all the report IDs
https://api.powerbi.com/v1.0/myorg/admin/reports/{reportId}/users
