### ISSUE TITLE
Can GETDATA be used with executeQueries

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#87]
Might be a bit off, but I need to query a table in a dataset that I don't have access to edit (the Usage Metrics dataset) and thought about using the GETDATA function in the customer connector. Two things I see as challenges is there is no ability to add a request body that contains the query and this is a POST method instead of a GET. Now I know this maybe a less than performant way of getting the data, but a) its a fairly small recordset and b) at my client I cannot get appropriate permissions to read the Event logs using GETActivity. 

Is it possible (i.e. a technical reason why it wouldn't work) to add this method to the connector? If so, I may give it a go.

Thanks

**Comment by migueesc123** [comment]
I haven't tried adding such function before, but technically it would be possible. It just wouldn't be easy for an end-user to figure out how to use it.
It also depends on what that endpoint expects, and if it uses some scopes or resourceUri which is different than the one that I'm using for the connector.

If you figure things out, we can definitely test it and merge it.
