### ISSUE TITLE
Use of Connector in a Dataflow

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#89]
I tried transporting my power query code from Power BI Desktop to a dataflow. The connector cannot sign in. I get the following message. I am connecting through the same gateway that the power bi dataset is using to refresh. So I know all that works.
I pasted the M code from PBI desktop to a blank query in the dataflow. Selected the same gateway. Click Next, and I get the message ![image](https://user-images.githubusercontent.com/19497071/135655173-1060ca3b-b3f7-4548-a82a-bd51dbf57451.png) I click on configure connection and get this dialog.
![image](https://user-images.githubusercontent.com/19497071/135655309-a492a952-3b6d-4c55-be1a-6d3c1ad0c525.png)
Click connect, it started to refresh and then goes back to the please specify how to connect.
I click the configure connection again, this time click Sign in as a different user... the login window briefly appears, then goes away and I get this message.

![image](https://user-images.githubusercontent.com/19497071/135655590-c86b5ddc-75df-4f04-8a30-56921263ea1a.png)

I've made sure that https://app.powerbi.com/ has popups enabled. 

Is there some sort of technical limitation as to why this wouldn't work in a dataflow?

**Comment by klinejordan** [comment]
Unfortunately custom connectors are not yet supported in dataflows
