### ISSUE TITLE
the field 'capacityId' of the record wasn't found

### ISSUE THREAD

**Issue by SergiyVV** [migueesc123/PowerBIRESTAPI#9]
Hi Miguel,

Regarding 'Get Groups' API:
https://api.powerbi.com/v1.0/myorg/groups

If a workspace is on a dedicated capacity (isOnDedicatedCapacity = true) this API (Get Groups) returns 'capacityId' column of workspace's data record.
If a workspace isn't on a dedicated capacity (isOnDedicatedCapacity = false) this API (Get Groups) does not return 'capacityId' column among other column of workspace's data record.

There are cases when some of the workspaces are on a dedicated capacity and others are not. When this happens PowerBIRESTAPI.GroupsDatasets function fails to transform records with different column sets to a table:
![ToTable](https://user-images.githubusercontent.com/52447998/63279935-8ef68a80-c2b2-11e9-8dba-03047b200846.png)
As a result data gets truncated on a record with error:
![ToTable_1](https://user-images.githubusercontent.com/52447998/63280450-7a66c200-c2b3-11e9-8908-e1a9dd01171c.png)

The data returned is not consistent.

**Comment by migueesc123** [comment]
Thanks for reporting this, @SergiyVV !
Truthfully, I don't have a timeline on when I'd have time to tackle this, but if you happen to have the solution to it, you can send a pull request to modify the code to this repo. Any contributions are greatly appreciated!

**Comment by klinejordan** [comment]
I fixed this in the latest release so you shouldn't see this issue anymore. The fix was to enumerate the columns explicitly and use MissingField.UseNull in the Table.FromRecords function that adds a column from the JSON returned by the API.

**Comment by migueesc123** [comment]
Thank you, Jordan!
