### ISSUE TITLE
DatasetToDataflowLinks not returning complete results

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#90]
I have dataflows that are used in datasets published to the service that appear to have a link with some datasets but not others. It may have to do with what connector being used, Power BI Dataflows or Power Platform dataflows. I assume if this is the case this is a bug in the REST API?  Has anyone run into this before?

Thanks

**Comment by migueesc123** [comment]
If you try using any other tool to query the api, do you get the same results that the connector shows you? Or are they different?

**Comment by relax528** [comment]
@klinejordan I see you tagged with a bug, is that a bug in the connector or a bug in the API? I can retest if necessary using Postman to see if the results differ.

**Comment by klinejordan** [comment]
This is a big in the API and the service - if you look at the lineage view for datasets using PowerPlatform.Dataflows it's also broken there.

**Comment by klinejordan** [comment]
This was fixed a while ago by Microsoft - there's still an issue with Upstream Dataflows using PowerPlatform.Dataflows() as reported in #145
