### ISSUE TITLE
Power BI Gateway Refresh

### ISSUE THREAD

**Issue by MartinSpalding** [migueesc123/PowerBIRESTAPI#92]
Hi,

I successfully added this connector to our on-prem gateway server where datasets using this connector were successfully refreshing until a few days ago. The errors I am receiving don't flag for all AppWorkspace keys, for example "Datasets" but they do flag for "Workspaces" and "Reports" but only when attempting to refresh the datasets in the PBI Service, everything refreshes fine within the Power BI Desktop application.

"Workspaces" error: 

The column 'Workspace Type' of the table wasn't found. Table: Workspaces

"Reports" error:

The 'endorsementDetails' column does not exist in the rowset. Table: Reports

Any help appreciated.

Martin.

**Comment by migueesc123** [comment]
Hey @MartinSpalding 

Could you share the M code for the queries that are giving you those issues?

one thing is to also make sure that you're using the same user to authenticate on the power bi service as you do in the power bi desktop when you create the report, otherwise there might be the possibility that the username / credentials that you're using on the cloud don't have the same permissions / access as the ones that you used in Power BI Desktop.

**Comment by MartinSpalding** [comment]
Thanks for your reply. I'm using the same user on desktop as service. Here's the "Workspaces" M-code, there is a "Workspace Type" column but I'm not sure why the gateway has an issue with this?...

let
    Source = PowerBIRESTAPI.Navigation(),
    AppWorkspace = Source{[Key="AppWorkspace"]}[Data],
    Workspaces1 = AppWorkspace{[Key="Workspaces"]}[Data]
in
    Workspaces1

**Comment by MartinSpalding** [comment]
Full error:

Data source error: {"error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","pbi.error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","parameters":{},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2147467259"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"The column 'Workspace Type' of the table wasn't found."}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2147467259"}},{"code":"Microsoft.Data.Mashup.ValueError.Detail","detail":{"type":1,"value":"Workspace Type"}},{"code":"Microsoft.Data.Mashup.ValueError.Reason","detail":{"type":1,"value":"Expression.Error"}}],"exceptionCulprit":1}}} Table: Workspaces.
Cluster URI: WABI-US-NORTH-CENTRAL-B-redirect.analysis.windows.net

**Comment by migueesc123** [comment]
I'm not entirely sure what could be happening. From a purely code standpoint, it looks good.

I tested the connector a few months ago and it was working without issues. What's more troubling is that it works for you in Power BI Desktop, but not in the Service - that is really odd.

Nevertheless, you could try and debug the piece of code that runs for that query or modify it to see what could be happening. Below is the link to that piece of code:
https://github.com/migueesc123/PowerBIRESTAPI/blob/6405c320938ef7705a46f3e22edb0d5a2f4ebdbe/Power%20BI%20API/Power%20BI%20API/PBIAPI.pq#L290-L298

**Comment by MartinSpalding** [comment]
Just for reference, I fixed this by changing the M-Code to the below, i.e. filtering the navigation table then expanding out the columns for that filter. I'm not sure why this works and the other doesn't but seems an easy fix. The offending column "Workspace Type" can be included this way with no issues:

let
    Source = PowerBIRESTAPI.Navigation(),
    AppWorkspace = Source{[Key="AppWorkspace"]}[Data],
    #"Filtered Rows1" = Table.SelectRows(AppWorkspace, each ([Name] = "Workspaces")),
    #"Expanded Data" = Table.ExpandTableColumn(#"Filtered Rows1", "Data", {"Workspace ID", "Is Read Only", "Is On Dedicated Capacity", "Workspace Name", "Workspace Type", "Capacity ID"}, {"Workspace ID", "Is Read Only", "Is On Dedicated Capacity", "Workspace Name", "Workspace Type", "Capacity ID"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Data",{{"Is Read Only", type logical}, {"Is On Dedicated Capacity", type logical}, {"IsLeaf", type logical}, {"ItemName", type text}, {"ItemKind", type text}, {"Capacity ID", type text}, {"Workspace Name", type text}, {"Workspace ID", type text}, {"Key", type text}, {"Name", type text}, {"Workspace Type", type text}})
in
    #"Changed Type"

**Comment by migueesc123** [comment]
adding @klinejordan and @ImkeF to see if they might have something to add or any reasoning behind this.

**Comment by ImkeF** [comment]
Cannot repo as well - refresh through gateway in the service is running smoothly for me.
Agree that the error message is really strange and doesn't make any sense to me.

**Comment by MartinSpalding** [comment]
Thanks ImkeF, what gateway version are you running? I'm on version: 3000.96 (current version -1).

Thanks.

**Comment by MartinSpalding** [comment]
Now I'm getting a the refresh error "The column 'Column1' of the table wasn't found." with the below M-code. Any help appreciated...

let
    Source = PowerBIRESTAPI.Navigation(),
    Functions = Source{[Key="Functions"]}[Data],
    GETData1 = Functions{[Key="GETData"]}[Data],
    #"Invoked FunctionGETData1" = GETData1("pipelines"),
    value = #"Invoked FunctionGETData1"[value],
    #"Converted to Table" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "displayName", "description"}, {"id", "displayName", "description"})
in
    #"Expanded Column1"

**Comment by MartinSpalding** [comment]
This was permissions in the end, no data was returning for "pipelines" hence the "Column1" error. The functions call requires elevated permissions for some reason.
