### ISSUE TITLE
Ability to pulls Apps and App Users

### ISSUE THREAD

**Issue by pb1051** [migueesc123/PowerBIRESTAPI#93]
This is a great custom connector. I am administrating PBI solo at my company and would love to have a little more information on which users have access to the various Apps.

Would it be possible to add this functionality as well?

**Comment by migueesc123** [comment]
Hey!
I've just had a major change in roles thanks to my new job, so for the foreseeable future I'll primarily be focusing on trying to be the best that I can at my new job and finish some of my other personal projects.

Not sure if perhaps @klinejordan or @ImkeF  would have time to look into this. Nevertheless, the repo is completely open to any forks / PRs so you can send any changes that you'd like to make to the custom connector and we could review it.

**Comment by klinejordan** [comment]
@pb1051 This is now available in the latest .mez file. Thanks for the feedback and sorry this took a while to get done - I won't go into the full details but this particular API call is more difficult than others to handle.

**Comment by pb1051** [comment]
I'm currently away from my PC for about 2 weeks. I'll try to confirm when I
return. I'm snoozing this notification until then and will provide feedback.

**Comment by pb1051** [comment]
Thanks @klinejordan . I seem to not be able to view this data anyways because my org doesn't allow me admin access. I'm sure there are users that will definitely profit from your new development and I'd like to say thanks!

**Comment by klinejordan** [comment]
Thanks @pb1051, good luck administering power bi without having the pbi admin role

**Comment by pb1051** [comment]
Haha. Thanks! It's miserable.
