### ISSUE TITLE
Power BI API connector dataset is not refreshable in Power BI service

### ISSUE THREAD

**Issue by Krishna1805** [migueesc123/PowerBIRESTAPI#94]
Hi, 
The below tables from the Power BI API connector are not refreshable in Power BI Service.
-Capacity refreshables
-Dataset Datasources
-Dataflow Datasources
-Gateway Datasource status
-Gateway Datasources
-Gateway Datasource users
I have installed Personal gateway in my computer to test the refresh of the dataset based on the above tables but I am getting the error.
![gateway error](https://user-images.githubusercontent.com/38653619/144815836-95ec6039-7775-4848-91f6-6eaa89a55c98.PNG)

Could you please help me how to refresh these tables?

Regards,
Krishna

**Comment by migueesc123** [comment]
Hey @Krishna1805 !

I've just tested on my end and the connector appears to be working correctly. There might be a misconfiguration at your gateway level. I'd recommend opening up a Power BI Pro support ticket so you can get assistance from Microsoft in troubleshooting the scenario in detail. Unfortunately, the errors given by the screen that you're looking at are not so descriptive so it's pretty difficult to tell what might be happening but i'd try to hit that "discover data sources" hyperlink that you have to see if it does anything.

Best!
