### ISSUE TITLE
Question: Follow pattern for using Graph API

### ISSUE THREAD

**Issue by relax528** [migueesc123/PowerBIRESTAPI#98]
Is there any reason I could use this project as a foundation to create a connector to access the Graph REST  API to pull Tasks by Planner data into Power BI? I would think that following the same authentication, the rest would be to build out functions for each of the desired methods. Is that a fair assumption?

**Comment by migueesc123** [comment]
Haven't looked at the documentation for the Graph REST API, so I can't comment on that but if it uses the same authentication then you should be able to copy / paste what I did on this one and apply it on your end.

However, i'd still suggest that you check the official documentation for the custom connectors to have a better idea of what needs to be done when using AAD. If you try to use something around scopes, then you'll need to use the OAuth authentication instead to have full control and use your own application and such.

best of luck!
