### ISSUE TITLE
Dataset datas sources table not refreshing in Power BI service

### ISSUE THREAD

**Issue by Krishna1805** [migueesc123/PowerBIRESTAPI#99]
The dataset datasources(admin) table is not refreshing in the Power BI service but it is working in power bi desktop,
I have installed gateway in my laptop and I am the Power BI service admin but still I am getting the gateway invalid credentials error.
All other tables are refreshing and using the same gateway.
![image](https://user-images.githubusercontent.com/38653619/151150347-a0e10290-eda3-4126-9e20-08a13cb04755.png)

**Comment by migueesc123** [comment]
hey!
I'd encourage you to get in touch with the Microsoft support team to raise a ticket / issue.

We are unable to provide any sort of reasoning as to why this isn't refreshing for you on the Power BI service. We, as the developers of the connector, don't have any tools to debug anything related to the gateway. You might be able to look at the logs and follow the standard procedure to troubleshoot gateway related issues.

**Comment by jgibbycsc** [comment]
Thanks @migueesc123 for responding.
